// CASO 1 — ECOS BAJO CUARENTENA
var CASE1 = {
  title: "Ecos Bajo Cuarentena",
  year: "2041",
  setting: "Estacion oceanografica abisal Nereida-9",
  tagline: "Tres muertes. Una red de trafico biologico. Un apagon que borro las pruebas.",
  intro: "Has accedido a la terminal de recuperacion de la estacion Nereida-9.\nFue sellada el 17 de noviembre de 2041 tras un \"accidente de presion\".\nTres de sus seis tripulantes figuran como bajas. Ningun informe oficial los menciona por nombre.\n\nEl sistema fue parcialmente borrado. Estas son las copias que sobrevivieron.\nLee los archivos. Sigue las pistas. Descubre quien mato a Borda, Aram y Tellez.",
  solveFile: "veredicto_final.evd",
  startFiles: [
    "/boot_notice.txt",
    "/audio/radio_emergencia_041.transcript",
    "/audio/audio_kern_02.transcript",
    "/logs/comedor_memo_77.txt",
    "/logs/turno_seguridad.log",
    "/personal/ficha_borda.txt",
    "/personal/ficha_kern.txt",
    "/comunicaciones/radiograma_entrada.txt",
    "/private/veredicto_final.evd"
  ],
  hints: [
    "Empieza con 'ls' en la raiz y lee boot_notice.txt para orientarte. Luego 'cd audio' y lee las transcripciones.",
    "En radio_emergencia_041, Kern menciona el apodo del pez del Dr. Borda. Ese apodo es la primera contrasena.",
    "cd audio → unlock audio_borda_01.enc FARO — El audio de Borda menciona el protocolo MAREA NUEVE.",
    "Usa 'examine 0317' para entender la anomalia del reloj maestro. Ese minuto borrado es la prueba de manipulacion.",
    "Usa 'examine marea9' para entender como se uso el protocolo de emergencia de forma criminal.",
    "Usa 'cd logs' y lee turno_seguridad.log. Voss tuvo una ausencia de 25 minutos sin justificar con la camara apagada.",
    "Usa 'examine biometria' para cruzar los movimientos de toda la tripulacion la noche del 17/11.",
    "Usa 'cd personal' y lee la ficha de Voss. Fue contratada directamente por Solvang, no por la estacion.",
    "Usa 'examine corporacion' para entender el papel de Solvang Corp y por que querian el agente B-9 a cualquier precio.",
    "Usa 'search biologia muestras' para revelar el informe de sustraccion de las muestras B-9 firmadas por m_voss.",
    "Usa 'examine taza' para entender como envenenaron a Borda. Luego 'examine alcaloide' para ver que tipo de veneno usaron.",
    "Usa 'search medico borda' para ver su historial. Alguien le nego el analisis toxicologico la noche del 16/11.",
    "Usa 'search protocolos marea9' para revelar el reporte de esclusa y la bitacora de Noel.",
    "Usa 'examine relay' para entender como Voss suplanto las credenciales de Aram. Luego 'examine rk44'.",
    "Usa 'cd ops' → unlock red_nucleo.enc RK44 para ver el historial completo de accesos al puerto oculto con nombres reales.",
    "La bitacora de Noel menciona el codigo RK-44 y el alias VANTA. Usa 'search finanzas vanta'.",
    "Usa 'cd comunicaciones' → unlock mensajes_borrados.enc VANTA para leer las ordenes directas que recibio Voss desde fuera.",
    "Usa 'search protocolos exportacion' para ver el manifiesto de carga con los bultos sin firma del Dr. Borda.",
    "El audio de Tellez revela el alias de operacion de Voss: EIDEN. Busca tambien 'search personal voss'.",
    "Usa 'examine voss' y 'profile voss' para armar el perfil completo. Luego cd private → unlock veredicto_final.evd EIDEN.",
    "Usa 'profile kern' y 'profile raal' para entender por que los supervivientes no pudieron evitar el crimen.",
    "Usa 'cd comunicaciones' y lee intercepcion_corporativa.txt. Ese correo fue la clave para procesar a los directivos de Solvang.",
    "Usa 'timeline' para ver la cronologia completa. Los accesos nocturnos de Voss al puerto RK-44 siguen un patron exacto.",
    "Comandos extra: map, timeline, evidence, profile [nombre], examine [termino]."
  ],
  map: "NEREIDA-9 — PLANTA PRINCIPAL (NIVEL 3)\n" +
    "Profundidad: 2.847 metros\n" +
    "═══════════════════════════════════════════════════\n" +
    "  ┌──────────┐  ┌──────────┐  ┌─────────────────┐\n" +
    "  │  MANDO   │  │  RADIO   │  │  LAB. BIOLOGIA  │\n" +
    "  └────┬─────┘  └────┬─────┘  └────────┬────────┘\n" +
    "       └─────────────┴────────────────┬─┘\n" +
    "  ┌────────────────────────────────────┴──────────┐\n" +
    "  │                PASILLO CENTRAL B              │\n" +
    "  └──────┬─────────────────────┬──────────────────┘\n" +
    "         │                     │\n" +
    "  ┌──────┴──────┐     ┌────────┴────────┐\n" +
    "  │   COMEDOR   │     │   ESCLUSA B  ←→ MAR │\n" +
    "  └─────────────┘     └─────────────────────┘\n" +
    "  ┌──────────┐  ┌──────────┐  ┌──────────┐\n" +
    "  │  MEDICO  │  │PERSONAL  │  │  OPS /   │\n" +
    "  │          │  │          │  │ SISTEMAS │\n" +
    "  └──────────┘  └──────────┘  └──────────┘\n" +
    "  ┌──────────┐  ┌──────────────────────────┐\n" +
    "  │  LEGAL   │  │ PRIVATE (acceso restringido)│\n" +
    "  └──────────┘  └──────────────────────────┘",
  profiles: {
    borda: "DR. ELIAS BORDA — Biologo Jefe\nEdad: 51. Especialidad: quimica marina y farmacologia de profundidades.\nAntiguedad en Nereida-9: 7 anos (desde la inauguracion).\nCaracter: meticuloso, desconfiado de los cambios de protocolo. Guardaba registros de audio de todo.\nSituacion: fallecido el 17/11/2041. Causa oficial no especificada. Causa real: investigar.\nConexion clave: descubrio el robo de muestras B-9 y lo confronto directamente con Voss.",
    voss: "MARA VOSS — Jefa de Seguridad\nEdad: 44. Formacion: ex-corporativa en Meridian BioSec (filial de Solvang Corp).\nAntiguedad en Nereida-9: 2 anos (contratada directamente por la corporacion).\nCaracter: eficiente, hermetica, no socializa con el resto de la tripulacion.\nSituacion: ausencia injustificada de 25 min el 17/11. Camara offline en ese intervalo.\nConexion clave: accesos nocturnos regulares al puerto RK-44. Alias de operacion: EIDEN.",
    kern: "LIA KERN — Tecnico de Radio y Comunicaciones\nEdad: 33. Especialidad: telecomunicaciones subacuaticas y sistemas de emergencia.\nAntiguedad en Nereida-9: 4 anos.\nCaracter: observadora, muy apegada al Dr. Borda (relacion de mentor/alumna).\nSituacion: superviviente. Estuvo en la cabina de radio cuando ocurrio el incidente.\nConexion clave: unica testigo directa del comportamiento de Voss antes de la muerte de Borda.",
    aram: "NOEL ARAM — Ingeniero de Sistemas\nEdad: 38. Especialidad: redes internas y sistemas de presion.\nAntiguedad en Nereida-9: 5 anos.\nCaracter: analitico, poco sociable. Documentaba todo en bitacoras manuscritas.\nSituacion: fallecido el 17/11/2041. Segun su propia nota, fue obligado a abrir la esclusa.\nConexion clave: descubrio el puerto RK-44 y el codigo de salida VANTA antes de morir.",
    tellez: "SIRA TELLEZ — Analista Juridica\nEdad: 29. Especialidad: cumplimiento normativo y auditoria de contratos.\nAntiguedad en Nereida-9: 1 ano (contratada para auditar operaciones internas).\nCaracter: discreta, pero muy persistente con los numeros. Guardaba copias de todo.\nSituacion: fallecida el 17/11/2041. Habia rastreado el flujo financiero hasta el alias Eiden.\nConexion clave: su grabacion de audio es la que vincula directamente a Voss con la operacion.",
    raal: "CMD. IVO RAAL — Comandante de Estacion\nEdad: 58. Formacion: marina mercante y gestion de instalaciones offshore.\nAntiguedad en Nereida-9: 7 anos.\nCaracter: formal, por-el-libro, pero protector de su tripulacion.\nSituacion: superviviente. Fue encerrado en modulo de contencion por protocolo durante el incidente.\nConexion clave: dejo la nota de boot_notice.txt. Sospechaba que el informe oficial era falso."
  },
  examine: {
    taza: "La taza de ceramica azul del Dr. Borda. Siempre cafe sin azucar, segun los registros del comedor.\nEsa noche la taza fue encontrada rota en la bandeja tecnica a las 01:10.\nEl memo del comedor indica que olía diferente a cafe normal.\nUn alcaloide vegetal en bebida caliente sería casi indetectable al gusto.",
    esclusa: "La Esclusa B es la unica compuerta de acceso directo al exterior de la estacion.\nEsta ubicada al final del Pasillo B, entre el comedor y el laboratorio de biologia.\nOpera en dos modos: automatico (gestion central) y manual (requiere autorizacion de dos operadores).\nEl evento del 17/11 a las 03:17 carece de firma digital — lo que es tecnicament imposible en modo normal.",
    "b9": "Agente biologico experimental catalogado en el laboratorio de biologia de Nereida-9.\nClasificacion: neurotrofico marino de origen abisal — aun sin nombre comercial.\nFue descubierto por el Dr. Borda en 2039 en las muestras del zanjón de Nereida.\nValor estimado en el mercado farmaceutico no regulado: desconocido, pero extremadamente alto.\nEl volumen de las muestras bajo un 41% sin justificacion entre el 13 y el 15 de noviembre.",
    alcaloide: "Compuesto quimico de origen vegetal (o sintetico derivado) con efectos sobre el sistema nervioso.\nEn dosis acumulativas pequenas durante tres o cuatro dias puede simular insuficiencia cardiaca.\nEl Dr. Borda, siendo farmacologo, reconocio el patron en su propia sintomatologia.\nEl compuesto mas probable: derivado de aconitina o cicutoxina, solubles en agua caliente.",
    vanta: "Alias de operacion utilizado en todas las transferencias financieras irregulares rastreadas por Noel Aram.\nApunta a una cuenta offshore sin titular identificado.\nEste alias conecta el puerto de red RK-44 con movimientos de fondos exteriores a la estacion.\nEl nombre de la cuenta corporativa de respaldo era Solvang Asset Trust.",
    raal: "El Comandante Raal fue el primero en sospechar del informe oficial.\nDurante el incidente estuvo encerrado en el modulo de contencion — protocolo de emergencia activado automaticamente.\nEste protocolo solo puede activarse desde el puesto de control de seguridad. Es decir, desde el puesto de Voss.\nSu nota en boot_notice.txt fue redactada desde un terminal de respaldo sin conexion a la red principal.",
    relay: "Dispositivo de comunicacion de red de baja frecuencia usado para acceder a puertos de respaldo.\nNoel Aram descubrio uno conectado al bus de datos de su terminal el 13 de noviembre.\nEste tipo de relay permite suplantar credenciales de usuario sin dejar huella en el log principal.\nEs el metodo mediante el cual alguien accedio al puerto RK-44 bajo el nombre de usuario n9_sec.",
    "0317": "La marca de tiempo 03:17 del 17 de noviembre no existe en el reloj maestro de la estacion.\nNoel Aram explica en su bitacora que esto es posible usando un paquete de autorizacion duplicado.\nEn la practica significa que alguien borro esos 60 segundos del historial oficial.\nEl reporte de la esclusa lo llama 'evento huerfano': un evento sin firma digital registrada.",
    borda: "El Dr. Elias Borda era la persona con mayor conocimiento cientifico de la estacion.\nDescubrio el robo de muestras B-9 el 15 de noviembre. Lo confronto con Voss directamente.\nSabia que estaban envenenandole pero no podia probarlo sin un analisis de sangre completo.\nGrababa registros de audio privados usando el nombre de su pez mascota como contrasena: FARO.",
    voss: "Mara Voss llego a Nereida-9 contratada directamente por la corporacion, saltandose el proceso interno.\nSu contrato original estaba firmado bajo el alias operativo EIDEN.\nTenia acceso permanente al puesto de control de seguridad y al sistema de esclusa.\nSus accesos nocturnos al puerto RK-44 siguieron un patron exacto: siempre entre las 03:00 y las 03:05.",
    noel: "Noel Aram era el unico que podia entender realmente como habian manipulado la red de la estacion.\nDescubrio el relay en su terminal y lo documento en su bitacora antes de ser neutralizado.\nSu nota al margen del reporte de la esclusa dice 'Me obligaron'. Fue amenazado para abrir la compuerta.\nMurio junto con Borda y Tellez en la esclusa B.",
    kern: "Lia Kern fue la primera en levantar la voz sobre la muerte de Borda.\nIntento contactar a Raal cinco veces sin exito. El comandante estaba en contencion.\nSu observacion mas importante: Voss fue la primera en limpiar el espacio de Borda antes de que llegara nadie.\nSu tercer audio (kern_03) contiene detalles sobre el comportamiento de Voss en las 48 horas previas.",
    tellez: "Sira Tellez habia rastreado el flujo financiero usando solo los documentos legales de la estacion.\nDescubrio que el alias EIDEN aparecia en contratos firmados antes de que Voss llegara a Nereida-9.\nSu grabacion de audio es la prueba mas directa del vinculo entre Voss y la operacion VANTA.\nFue a la esclusa B esa noche porque Noel le habia pedido ayuda para documentar lo que habia encontrado.",
    eiden: "Nombre utilizado por Mara Voss como alias de operacion antes de su contratacion en Nereida-9.\nAparece en contratos firmados en Marsella (2038-2039) para exportacion de material biologico no regulado.\nEs tambien el apellido de soltera que Voss usaba en sus documentos previos a la boda.\nEl contrato en /personal/contrato_voss.enc esta firmado bajo ese nombre.",
    faro: "El nombre del pez ciego del Dr. Borda. Un pez de las profundidades sin pigmentacion.\nBorda lo usaba como metafora: 'un faro cuando todo se va al fondo'.\nEra tambien la contrasena de sus registros de audio privados.\nLia Kern lo menciona en la primera transcripcion de radio de emergencia.",
    marea9: "Nombre del protocolo de contingencia de la esclusa B.\nPermite cambiar la esclusa a modo manual desde un terminal de movilidad sin autorizacion doble.\nEste protocolo existe para emergencias reales. Fue usado de forma criminalmente incorrecta el 17/11.\nSolo el personal de seguridad conocia su nombre y procedimiento de activacion.",
    rk44: "Codigo del puerto de red de respaldo de Nereida-9.\nPermite acceso externo al bus de datos de la estacion saltando los logs principales.\nSolo lo conocian el Dr. Borda (en calidad de investigador principal) y Noel Aram (sistemas).\nVoss lo obtuvo robando el terminal de Aram mediante un relay instalado subrepticiamente.",
    nereida: "La estacion Nereida-9 fue construida en 2034 por el consorcio Solvang Corp / Marina Profunda SA.\nSe ubica en la fosa abisopelágica de Nereida, frente a las islas Canarias orientales.\nFue diseñada para investigacion biologica y geologica en profundidades superiores a 2.000 metros.\nSus tres modulos de vida pueden sellarse de forma independiente en caso de emergencia.",
    biometria: "El sistema biometrico de Nereida-9 registra movimiento de todos los tripulantes mediante sensores.\nLa ultima lectura del Dr. Borda fue a las 23:58 en el pasillo de biologia, segun el log.\nNoel Aram desaparece del registro biometrico a las 03:09 — 8 minutos antes del evento huerfano.\nLia Kern aparece en la cabina de radio sin interrupcion desde las 22:00 hasta las 07:00.",
    manifiesto: "El manifiesto de carga de Nereida-9 lista los suministros y exportaciones de cada ciclo.\nEn el ciclo de octubre-noviembre 2041, hay tres bultos marcados 'muestra biologica Cod. NTX' sin firma de autorizacion del biologo jefe.\nEl Dr. Borda era el unico con autoridad para firmar exportaciones biologicas. El nunca firmo esos bultos.",
    corporacion: "Solvang Corp es la empresa matriz que financiaba las operaciones de Nereida-9.\nSu filial de seguridad (Meridian BioSec) fue la que contrato directamente a Mara Voss.\nVoss recibia instrucciones paralelas de Meridian BioSec al margen del canal oficial de la estacion.\nLa intercepcion corporativa en /comunicaciones/ contiene una de esas instrucciones."
  },
  timeline: [
    { time: "10/11  03:02", event: "Primer acceso nocturno de m_voss al puerto RK-44 (exportacion VANTA)", trigger: "/ops/red_nucleo.enc" },
    { time: "12/11  02:58", event: "Segundo acceso de m_voss al puerto RK-44", trigger: "/ops/red_nucleo.enc" },
    { time: "13/11  ~18:00", event: "Noel Aram descubre un relay en su terminal. Lo documenta en su bitacora.", trigger: "/ops/bitacora_noel.txt" },
    { time: "14/11  03:00", event: "Tercer acceso de m_voss al puerto RK-44", trigger: "/ops/red_nucleo.enc" },
    { time: "15/11  02:30", event: "Voss accede al laboratorio de biologia sin autorizacion. Kern lo atestigua.", trigger: "/bio/nota_kern_observaciones.txt" },
    { time: "15/11  ~16:00", event: "Borda detecta la sustraccion de 185 ml de muestra B-9. Ultimo acceso firmado: m_voss.", trigger: "/bio/informe_muestras_b9.txt" },
    { time: "15/11  noche", event: "Borda comienza a detectar trazas de alcaloide en sus bebidas. Inicia registros de audio.", trigger: "/audio/audio_borda_01.enc" },
    { time: "16/11  03:00", event: "Cuarto acceso de m_voss al puerto RK-44", trigger: "/ops/red_nucleo.enc" },
    { time: "16/11  ~20:00", event: "Borda confronta a Voss. Llama a Kern esa noche: 'Si no te llamo manana, busca mi pez'.", trigger: "/bio/nota_kern_observaciones.txt" },
    { time: "17/11  22:10", event: "Borda consume cafe en el comedor. Voss solicito cierre de la maquina norte sin formulario.", trigger: "/logs/comedor_memo_77.txt" },
    { time: "17/11  00:05", event: "Voss abandona el puesto de control sin justificacion (25 minutos). Camara offline.", trigger: "/logs/turno_seguridad.log" },
    { time: "17/11  00:32", event: "Voss regresa y notifica 'sin novedad' al comandante Raal.", trigger: "/logs/turno_seguridad.log" },
    { time: "17/11  02:58", event: "Inicio de secuencia en Esclusa B. Usuario: n9_sec (suplantacion con relay).", trigger: "/ops/reporte_esclusa.log" },
    { time: "17/11  03:17", event: "EVENTO HUERFANO: esclusa abierta. Noel obligado. Borda, Aram y Tellez: fallecidos.", trigger: "/ops/reporte_esclusa.log" },
    { time: "17/11  09:15", event: "Raal descubre los cuerpos. Activa sellado de emergencia. Primer comunicado oficial.", trigger: "/boot_notice.txt" }
  ],
  filesystem: {
    type: "dir",
    children: {
      "boot_notice.txt": { type: "file", content: "NEREIDA-9 / TERMINAL DE RECUPERACION\nSesion restaurada desde respaldo parcial — integridad: 62%\nFecha de sellado: 17 de noviembre de 2041\n\nTRIPULACION ASIGNADA (ciclo nov. 2041):\n  Dr. Elias Borda     — Biologo jefe\n  Ing. Noel Aram      — Sistemas / Infraestructura\n  Lia Kern            — Tecnico radio y comunicaciones\n  Sira Tellez         — Analista juridica\n  Mara Voss           — Jefa de seguridad\n  Cmd. Ivo Raal       — Comandante\n\nESTADO DE MODULOS:\n  Modulo A (Mando / Radio):      SELLADO\n  Modulo B (Biologia / Medico):  SELLADO\n  Modulo C (Ops / Legal):        SELLADO\n  Esclusa B:                     BLOQUEADA (post-evento)\n\nNota del administrador (Ivo Raal, terminal de respaldo):\n'No confies en los reportes de incidente enviados a la corporacion.\nTres de mis seis tripulantes no aparecen en ningun informe oficial.\nLos audios tienen mas verdad que los formularios.\nSi alguien llega hasta aqui, que sepa que esto no fue un accidente.'\n\nDirectorios: /audio  /logs  /ops  /bio  /medico  /personal  /comunicaciones  /legal  /private\nComandos: help, ls, cd, read, unlock, search, examine, profile, timeline, evidence, map, hint, clear, menu" },
      audio: {
        type: "dir",
        children: {
          "radio_emergencia_041.transcript": { type: "file", content: "[Transcripcion de audio — Radio Interna — 17/11/2041]\n[Audio inicia 00:03]\n\nVoz 1 (Lia Kern): Central, aqui Radio Interna. No tengo visual de Borda en enfermeria.\nVoz 2 (Control): Confirmado. Ultima lectura biometrica a las 23:58 en pasillo de biologia.\n\n[Ruido metalico lejano]\n\nVoz 1: Oi de nuevo ese golpe en la esclusa. No deberia haber nadie ahi a esta hora.\nVoz 2: Mantente en cabina. No abras la puerta bajo ningun concepto.\n\n[Audio salta. Marca 00:49]\n\nVoz 1: El doctor siempre se reia de mis supersticiones.\n       Decia que su pez ciego era su faro cuando todo se iba al fondo.\n       Lo llamaba FARO. Una especie sin ojos que vive en la oscuridad total.\n       Cuando todo sea oscuro, busca a FARO, me dijo una vez.\nVoz 2: Lia, repite esa ultima parte.\nVoz 1: Que su mascota se llamaba igual que una luz para barcos. Eso es todo.\n\n[Interferencia larga — 38 segundos]\n\nVoz 1 (susurrando): Si alguien revisa este archivo despues...\n                    busquen el registro privado de Borda. El saba lo que pasaba.\n\n[Audio termina 01:12]" },
          "audio_kern_02.transcript": { type: "file", content: "[Transcripcion de audio — Cabina de Radio — 17/11/2041]\n[Audio inicia 14:20 — dia siguiente al incidente]\n\nVoz (Lia Kern): He intentado cinco veces contactar con el comandante Raal.\nVoz (tecnico guardia): El comandante esta en modulo de contencion por protocolo.\nVoz (Kern): Alguien activo ese protocolo de contencion. Eso no ocurre solo.\n            Y ocurrio justamente cuando Raal queria ir a la esclusa.\n\nVoz (tecnico): La senora Voss dijo que fue estres prolongado en los tres tecnicos.\nVoz (Kern): El Dr. Borda no estaba estresado. Estaba envenenado. Yo lo vi.\n            Vi la taza cuando limpiaron su modulo. Olia diferente al cafe normal.\n            Era algo amargo, quimico. No me lo pude sacar de la nariz.\n\nVoz (tecnico): La senora Voss fue la que reporto el incidente.\nVoz (Kern): Y fue tambien la primera en entrar al modulo de Borda antes de que llegara nadie.\n            El cuaderno de apuntes de Elias habia desaparecido cuando entre yo.\n\n[Interferencia de 12 segundos]\n\nVoz (Kern): Si algo me pasa, mis notas estan en /bio. Todas.\n            El jefe de seguridad ES el problema. No el estres. Ella.\n\n[Audio cortado 14:41]" },
          "audio_kern_03.transcript": { type: "file", hidden: true, content: "[Transcripcion de audio — Cabina de Radio — 18/11/2041]\n[Audio inicia 09:15 — segundo dia tras el incidente]\n\nVoz (Lia Kern): Esto es para el registro. Por si alguien lo necesita despues.\n\nEl jueves por la noche (16/11), antes de que ocurriera todo,\nvi a la senora Voss en el pasillo B a las 23:30 con una bolsa de mano pequena.\nEsa bolsa no formaba parte de ningun equipo de seguridad que yo reconociera.\n\nEl viernes (17/11) a las 01:15 note que la luz del modulo del Dr. Borda estaba encendida.\nEso era muy inusual. El siempre la apagaba antes de medianoche.\nLlame a la puerta. No respondio. No force la entrada porque no quise romper protocolo.\n\nMedia hora despues vi a Voss salir del pasillo B. Sin la bolsa.\nLe pregunte si habia visto al Dr. Borda. Me dijo que descansaba.\nSus manos temblaban ligeramente.\n\nEsa fue la ultima vez que hable con ella antes de que todo se cerrara.\n\n[Silencio de 8 segundos]\n\nVoz (Kern): Cuiden a Ivo. El sabe mas de lo que ha podido decir.\n\n[Audio termina 09:44]" },
          "audio_borda_01.enc": { type: "file", locked: true, password: "FARO", content: "[Registro de audio privado — Dr. Elias Borda — 15/11/2041]\n[Audio inicia 00:07]\n\nVoz (Dr. Elias Borda): Registro privado. Si algo me sucede, este archivo es la prueba.\n\n[Respiracion agitada]\n\nVoz: He detectado trazas de un compuesto en mi taza tres noches consecutivas.\nDosis pequenas, acumulativas. El patron es consistente con un alcaloide de origen vegetal\no sintetico. A esas concentraciones no mata de inmediato. Lo hace parecer un fallo cardiaco.\n\nVoz: Hable con Noel esta tarde. Me confirmo algo que yo ya sospechaba:\nel sistema de esclusa cambia de modo manual solo cuando alguien activa el protocolo\nde contingencia desde dentro. El nombre del protocolo es MAREA NUEVE.\nNoel me dijo que ese protocolo no deberia conocerlo nadie ajeno a sistemas y seguridad.\n\n[Silencio de 6 segundos]\n\nVoz: Alguien ha alterado los registros de turno justo antes de las cero y cuarto.\nEl minuto 03:17 no deberia existir en los logs si el reloj maestro funciona correctamente.\nCruzad los horarios con el reporte de esclusa.\n\nVoz: He pedido a Sira Tellez que revise los contratos de aprovisionamiento del ultimo ciclo.\nHay bultos que salieron sin mi firma. Yo no autorize ninguna exportacion de muestras B-9.\n\nVoz (bajando la voz): No confies en la jefa de seguridad. Ella lo sabe todo. Y ella lo inicio.\n\n[Audio termina abruptamente 01:03]" },
          "audio_raal_interceptado.enc": { type: "file", hidden: true, locked: true, password: "MAREA9", content: "[Intercepcion de comunicacion interna — Cmd. Raal / desconocido — 16/11/2041]\n[Fuente: terminal de respaldo, modulo A]\n\nVoz 1 (Raal): Necesito acceso a los logs de esclusa del ultimo mes.\nVoz 2 (desconocido): Comandante, ese acceso requiere autorizacion de seguridad.\nVoz 1 (Raal): Soy el comandante de la estacion. Tengo autorizacion maxima.\nVoz 2: La senora Voss ha reclasificado esos registros como documentacion de nivel B-3.\n       Solo ella puede aprobar el acceso.\n\n[Pausa larga]\n\nVoz 1 (Raal, en voz baja): Escuchadme bien. Hay algo muy equivocado en esta estacion.\nLos tres tecnicos del modulo B han presentado sintomas neurologicos en las ultimas 48 horas.\nBorda me dijo que no era estres. Me dijo 'Ivo, alguien nos esta envenenando'.\nY ahora no puedo acceder a los registros de seguridad.\n\n[Ruido de conexion cortada]\n\nVoz 1: Aqui el comandante. Esta comunicacion queda como registro de mi objecion formal.\nSi algo pasa en las proximas 12 horas, la responsabilidad es de quien controla esos registros.\n\n[Fin de grabacion]" }
        }
      },
      logs: {
        type: "dir",
        children: {
          "comedor_memo_77.txt": { type: "file", content: "MEMO INTERNO — SERVICIO DE COMEDOR NOCHE\nTurno: 22:00–02:00  /  Responsable: T. Mena\nFecha: 17/11/2041\n\nINCIDENCIAS DE TURNO:\n  — El Dr. Borda pidio cafe sin azucar a las 22:10. Como siempre.\n  — La senora Voss (Seguridad) solicito a las 22:08 cerrar la maquina expendedora norte\n    por 'mantenimiento preventivo'. No presento ninguno de los formularios habituales.\n    La maquina estuvo cerrada unos 6 minutos. Luego Voss dijo que 'ya estaba bien'.\n  — A las 01:10 se encontro una taza rota en la bandeja tecnica lateral.\n    La taza tenia residuo de cafe y algo mas. Olia extrano. No lo registre en el momento.\n\nANOTACION AL MARGEN (tinta roja, letra diferente — posiblemente Kern):\n  'Quien escribe protocolos con nombres de mareas?\n   Vi en la pizarra del turno de seguridad: MAREA NUEVE, subrayado dos veces.\n   Si falta personal en el cambio de turno, revisad la esclusa antes que los dormitorios.'" },
          "turno_seguridad.log": { type: "file", content: "LOG OFICIAL DE TURNO — JEFA DE SEGURIDAD M. VOSS\nFecha: 17/11/2041  /  Turno: 22:00–06:00\n\n22:00  Inicio de turno. Revision perimetral modulos A, B, C.\n22:08  Accede a comedor. Supervisa servicio nocturno.\n22:14  Regresa a puesto de control principal.\n23:30  Revision de sistemas. Todo en parametros.\n00:05  Abandona puesto de control — MOTIVO: no registrado.\n00:30  Regresa a puesto de control.\n00:32  Notifica 'sin novedad' al comandante Raal via radio interna.\n01:00  Revision de pasillo B. Reporta normalidad.\n\nNOTA AUTOMATICA DEL SISTEMA (marcador rojo):\n  Ausencia no justificada: 00:05 — 00:30 (25 minutos).\n  Camara de pasillo B OFFLINE durante ese intervalo exacto.\n  El apagado de camara no consta en ningun registro de mantenimiento del turno.\n  Protocolo exige notificar al comandante cualquier ausencia superior a 10 minutos." },
          "accesos_biometricos.log": { type: "file", hidden: true, content: "LOG DE ACCESOS BIOMETRICOS — NEREIDA-9\nPeriodo: 13/11 al 17/11/2041\n\nDR. ELIAS BORDA:\n  15/11  02:30  Lab. Biologia (entrada)\n  15/11  04:15  Lab. Biologia (salida)\n  16/11  20:10  Comedor (entrada), 20:55 (salida)\n  17/11  22:05  Comedor (entrada), 22:40 (salida) — ULTIMA LECTURA\n  17/11  23:58  Pasillo Biologia — ULTIMA LECTURA REGISTRADA\n\nING. NOEL ARAM:\n  13/11  17:45  Terminal OPS (entrada)\n  16/11  21:30  Pasillo B (entrada)\n  17/11  03:09  Pasillo Esclusa B (entrada) — ULTIMA LECTURA REGISTRADA\n\nSIRA TELLEZ:\n  15/11  14:00  Legal (entrada)\n  17/11  02:57  Pasillo Esclusa B (entrada) — ULTIMA LECTURA REGISTRADA\n\nMARA VOSS:\n  17/11  22:00  Puesto control (entrada)\n  17/11  00:05  Puesto control (salida) — SIN REENTRADA HASTA 00:30\n  [NOTA: lectura biometrica suspendida en pasillo B durante ausencia]\n\nLIA KERN:\n  17/11  22:00  Cabina Radio (entrada)\n  17/11  07:02  Cabina Radio (salida)\n  [Sin interrupciones — coartada completa]" },
          "camaras_offline.log": { type: "file", hidden: true, content: "LOG DE INCIDENCIAS — SISTEMA DE CAMARAS\nNereida-9 / Periodo: 10/11 — 17/11/2041\n\nEVENTOS DE DESCONEXION:\n\n  10/11  02:55–03:10  Camara Pasillo B       — usuario: n9_sec\n  12/11  02:50–03:08  Camara Pasillo B       — usuario: n9_sec\n  14/11  02:55–03:06  Camara Pasillo B       — usuario: n9_sec\n  16/11  02:59–03:07  Camara Pasillo B       — usuario: n9_sec\n  17/11  00:05–00:30  Camara Pasillo B       — usuario: n9_sec\n\nNOTA DEL SISTEMA:\n  El usuario 'n9_sec' corresponde a la cuenta de servicio de seguridad.\n  Normalmente opera en modo automatico. Los apagados manuales requieren\n  confirmacion del jefe de turno. Ninguna de estas sesiones tiene confirmacion.\n\nNOTA MANUSCRITA (papel pegado al log impreso, letra de Noel Aram):\n  'La cuenta n9_sec no tiene credenciales propias.\n   Se activa con las claves del jefe de seguridad activo.\n   Quien apago esas camaras: Voss. Sin ninguna duda.'" }
        }
      },
      ops: {
        type: "dir",
        children: {
          "reporte_esclusa.log": { type: "file", hidden: true, content: "REPORTE DE EVENTOS — ESCLUSA B\nFecha: 17/11/2041  /  Modo activo: mantenimiento remoto\n\n02:58  Solicitud de prueba de sellado (usuario: n9_sec)\n03:04  Cambio a modo manual — origen: terminal de movilidad (Pasillo B)\n03:09  Puerta interna cerrada — lecturas biometricas de Aram, Tellez y Borda EN INTERIOR\n03:11  Solicitud de liberacion de puerta externa (usuario: n9_sec)\n03:17  EVENTO SIN FIRMA DIGITAL — REGISTRO HUERFANO\n        [El reloj maestro no registra este minuto en el historial sincronizado]\n03:18  Alarma local de la esclusa silenciada desde el interior\n03:22  Puerta externa abierta 4 segundos — presion igualada\n03:24  Estado restablecido (usuario: n9_sec) — puerta interna sin respuesta\n03:26  Sistema de emergencia de esclusa: OFFLINE\n\nNOTA AUTOMATICA: manipulacion de timestamp detectada — probabilidad 94%\n\nNOTA MANUSCRITA (N. Aram, interior de la cubierta del log):\n  'No es un fallo tecnico. Es una mano humana.\n   Me metieron aqui a punta de amenaza. Yo abri la puerta interna.\n   No tuve eleccion. Lo siento, Elias. Lo siento, Sira.'" },
          "bitacora_noel.txt": { type: "file", hidden: true, content: "BITACORA TECNICA — ING. NOEL ARAM\nFecha: 13 al 16 de noviembre de 2041\n\n--- 13/11 ---\nHe encontrado un relay de red conectado a mi terminal de sistemas.\nNo es equipo de la estacion. Alguien lo instalo mientras yo no estaba.\nEste tipo de dispositivo permite suplantar credenciales en el bus de datos.\nEs decir: alguien puede usar mis permisos sin que yo lo sepa.\n\n--- 14/11 ---\nConfirmado: el relay fue usado para acceder al puerto RK-44.\nEse puerto es una via de datos de respaldo que no aparece en los logs principales.\nSolo yo y el Dr. Borda sabiamos que existia. Y ahora tambien sabe quien instalo el relay.\n\nEl codigo del puerto: RK-44.\nEl codigo de salida de los datos exportados: VANTA.\n\n--- 16/11 ---\nHe rastreado cuatro accesos nocturnos al puerto RK-44 en los ultimos siete dias.\nSiempre entre las 03:00 y las 03:05. Usuario suplantado: n9_sec (cuenta de servicio de seguridad).\n\nBuscad los pagos bajo el alias VANTA.\nTodo el trafico financiero de esta operacion usa ese codigo.\nLa cuenta de destino esta fuera de la estacion. Offshore. No puedo rastrearla desde aqui.\n\nLe conte todo a Borda hoy. Me dijo que Sira Tellez puede cruzar esos datos con los contratos.\nMañana lo ponemos todo junto y vamos a Raal.\n\nFirmado: N. Aram\n\nP.D.: Si encuentran esto sin encontrarme a mi, sabed lo que significa." },
          "red_nucleo.enc": { type: "file", hidden: true, locked: true, password: "RK44", content: "DUMP PARCIAL DE RED — PUERTO OCULTO NEREIDA-9\nRecuperado de cache del bus de datos\n\nPUERTO: RK-44 (acceso de respaldo, no documentado en manual oficial)\nCODIGO DE SESION DE SALIDA: VANTA\n\nHISTORIAL DE ACCESOS AL PUERTO RK-44:\n  10/11  03:02 — usuario: m_voss  (1.4 GB exportados)\n  12/11  02:58 — usuario: m_voss  (0.9 GB exportados)\n  14/11  03:00 — usuario: m_voss  (2.1 GB exportados)\n  16/11  03:00 — usuario: m_voss  (1.7 GB exportados)\n\nPATRON: accesos nocturnos regulares, mismo usuario, mismo intervalo de tiempo.\nTipo de datos: muestras cifradas (extension .bio.enc) — origen: Lab. Biologia\n\nDESTINO EXTERNO (parcialmente recuperado):\n  Servidor de recepcion: VANTA-RELAY-07 [IP no resolvible desde esta red]\n  Identificacion del cliente: SOLVANG ASSET TRUST\n\nFRAGMENTO DE CACHE CIFRADO (descifrado parcialmente):\n  'Ella exigio cortar cabos antes del amanecer del ciclo 7.\n   Los tres tecnicos habian encontrado piezas del mismo puzzle por separado.\n   Voss los elimino antes de que pudieran unirlas.'" },
          "manifiesto_carga.txt": { type: "file", hidden: true, content: "MANIFIESTO DE CARGA — CICLO NOVIEMBRE 2041\nNereida-9 / Responsable: Mara Voss (Seguridad / Logistica)\n\nSALIDAS AUTORIZADAS:\n  3 x caja estandar material de laboratorio (consumibles)\n  2 x caja residuos no peligrosos (protocolo estandar)\n\nSALIDAS SIN FIRMA DEL BIOLOGO RESPONSABLE:\n  3 x bulto marcado 'MUESTRA BIOLOGICA COD. NTX'\n    — Firmado por: M. Voss\n    — Sin contrafirma del Dr. Borda (OBLIGATORIA por protocolo para material biologico)\n    — Destino declarado: 'laboratorio externo, clasificado'\n\nNOTA DE AUDITORIA (Sira Tellez, 15/11/2041):\n  'Estos tres bultos no tienen numero de expediente cientifico.\n   La firma de Voss no tiene autoridad para exportar material biologico.\n   El Dr. Borda no fue consultado. Se lo comunique hoy. Se puso palido.'\n\nNOTA AL MARGEN (letra de Borda, tinta roja):\n  'Yo nunca firme esto. Nunca. Mara: si lees esto, ya es demasiado tarde para ti.'" }
        }
      },
      bio: {
        type: "dir",
        children: {
          "nota_kern_observaciones.txt": { type: "file", hidden: true, content: "NOTAS DE CAMPO — LIA KERN\nSemana del 13 al 17 de noviembre de 2041\n\nLunes 13:\n  Vi a Voss en el laboratorio de biologia a las 02:30 de la madrugada.\n  No es su area de acceso habitual. Manipulaba las muestras del modulo B-9.\n  Le pregunte que hacia. Me dijo que 'revision rutinaria de seguridad'.\n  Nunca habia oido eso antes.\n\nMiercoles 15:\n  El volumen de la muestra B-9 habia bajado un 40% sin justificacion en el libro de registro.\n  Borda estaba muy agitado. Dijo que era imposible que se perdiera tanto por evaporacion.\n  La firma de ultimo acceso era m_voss.\n\nJueves 16:\n  Elias fue a hablar con Voss directamente a las 20:00. Fue al despacho de seguridad.\n  Me llamo a las 23:00. Estaba nervioso. Dijo textualmente:\n  'Lia, si no te llamo manana a las 09:00, busca mi pez.'\n  No entendia a que se referia hasta que recorde el audio de emergencia.\n\nViernes 17:\n  Borda no aparecio en el turno de manana. A las 09:15 lo encontraron.\n  Voss fue la primera en entrar a su modulo. La agenda de apuntes de Elias habia desaparecido.\n  No la vi cuando entre yo, diez minutos despues." },
          "informe_muestras_b9.txt": { type: "file", hidden: true, content: "INFORME DE CONTROL DE MUESTRAS — LABORATORIO BIOLOGIA\nResponsable: Dr. Elias Borda\nFecha de redaccion: 15/11/2041\n\nMUESTRA AFECTADA: B-9 (agente neurotrofico de origen abisal, sin clasificacion oficial)\nUbicacion: modulo de biologia, camara fria 4-B\n\nVOLUMEN AL INICIO DEL CICLO (01/11):   450 ml\nVOLUMEN ACTUAL (15/11):                265 ml\nDIFERENCIA NO JUSTIFICADA:             185 ml\n\nFIRMA DE ULTIMO ACCESO EN LOG DIGITAL: m_voss (sin autorizacion del biologo responsable)\nFECHA Y HORA:                          15/11/2041, 02:30\n\nEVALUACION:\nLa muestra B-9 no experimenta evaporacion apreciable en camara fria a -4°C.\nLa unica via de reduccion es extraccion mecanica. 185 ml equivalen a 9-10 dosis\nde concentrado puro, suficientes para contaminar agua, alimentos o bebidas de\ntoda la tripulacion durante semanas a dosis no letales.\n\nNOTA AL MARGEN (Borda, rotulador rojo):\n  'Si hay transaccion economica vinculada, buscad el alias VANTA.\n   Ese nombre aparece en el registro de red de Noel.'" },
          "registro_experimento.txt": { type: "file", hidden: true, content: "LIBRO DE REGISTRO — INVESTIGACION B-9\nDr. Elias Borda  /  Ciclos mayo 2040 — noviembre 2041\n\n--- NATURALEZA DEL AGENTE B-9 ---\nDescubierto en las muestras del zanjon Nereida (2.700 m) en octubre de 2039.\nPropiedad quimica: modula la actividad del sistema nervioso autonomo.\nEfecto en dosis bajas (cronica): deterioro cognitivo, letargia, muerte cardiaca aparente.\nEfecto en dosis medias: paresia muscular, confusion severa, inconsciencia.\nEfecto en dosis altas: fallo multiorganico en 2-6 horas.\n\n--- APLICACIONES POTENCIALES ---\nMedicas (supresion de dolor neuropatico severo): MUY PROMETEDOR.\nNo medicas: clasificadas como peligrosas en el protocolo etico firmado por todos los tripulantes.\n\n--- ULTIMA ENTRADA (14/11/2041) ---\nAlguien ha tomado 185 ml de la camara 4-B sin registrarlo.\nSi ese volumen se administra en dosis diarias en bebidas calientes (cafe, infusiones),\nel receptor no detectaria nada en los primeros dias.\nEl patron seria: debilidad progresiva, deterioro cardiaco aparente, muerte.\nSin analisis toxicologico especifico, pasaria por un fallo cardiaco natural.\n\nEsto no es especulacion. Esto es lo que me esta pasando a mi." },
          "ficha_agente_b9.enc": { type: "file", hidden: true, locked: true, password: "MUESTRA", content: "FICHA TECNICA CLASIFICADA — AGENTE BIOLOGICO B-9\nDocumento de acceso restringido — Dr. Borda / Corporacion Solvang\n\nNOMBRE QUIMICO: Nereidina-9 (denominacion de trabajo)\nCLASIFICACION CORPORATIVA: Activo de alto valor (AV-1)\n\nVALOR DE MERCADO ESTIMADO (concentrado puro, 100 ml):\n  Aplicacion medica legal:          aprox. 180.000 USD\n  Mercado no regulado (defensa/inteligencia): aprox. 2.400.000 USD\n\nESTATUS DE PROPIEDAD INTELECTUAL:\n  Derechos de descubrimiento: Dr. Elias Borda (personal)\n  Acuerdo de cesion firmado: PENDIENTE (Borda se nego en octubre 2041)\n  Comunicacion corporativa interna (Solvang):\n    'Si Borda no firma la cesion voluntariamente antes del fin del ciclo 7,\n     activar el protocolo de recuperacion de activos.'\n\nNOTA DEL AUDITOR:\n  'Protocolo de recuperacion de activos' es el eufemismo usado internamente\n  para eliminar fisicamente al investigador que posee los derechos.\n  Este documento establece el motivo real del asesinato del Dr. Borda." }
        }
      },
      medico: {
        type: "dir",
        children: {
          "historial_borda.txt": { type: "file", hidden: true, content: "HISTORIAL MEDICO — DR. ELIAS BORDA\nEnfermeria Nereida-9 / Ciclo noviembre 2041\n\nCONSULTAS REGISTRADAS (noviembre):\n  06/11  Revision rutinaria. Estado: optimo.\n  12/11  Consulta voluntaria. Sintomas: fatiga leve, sensacion de presion cardiaca.\n         Evaluacion: estres por jornadas largas. Sin medicacion.\n  14/11  Nueva consulta. Sintomas: fatiga acentuada, ligera perdida de coordinacion fina.\n         Borda: 'No es estres. He visto estos sintomas en experimentos de laboratorio.'\n         No se registro medicacion ni derivacion.\n  16/11  Consulta urgente nocturna. Borda llego a las 23:00 con taquicardia.\n         Solicito analisis de sangre completo con panel toxicologico.\n         SOLICITUD DENEGADA por la jefa de seguridad Voss, que estaba presente en enfermeria.\n         Motivo aducido por Voss: 'Procedimiento de analisis fuera de horario de enfermeria.'\n         BORDA: 'Esto es una emergencia medica. Exijo el analisis.'\n         VOSS: 'El comandante Raal ya ha sido informado. Descanse, doctor.'\n\nNOTA DEL SANITARIO (F. Adis, enfermero de guardia):\n  'Nunca habia visto a Voss en enfermeria. El doctor tenia razon en exigir el analisis.\n   Le hice un electrocardiograma rapido. Mostraba irregularidades leves pero reales.\n   Cuando sali a buscar los reactivos del panel toxicologico, Borda habia desaparecido.\n   Voss dijo que habia vuelto a su modulo.'" },
          "toxicologia.txt": { type: "file", hidden: true, content: "INFORME TOXICOLOGICO POST-MORTEM — DR. ELIAS BORDA\nPreparado por: F. Adis, Enfermero Senior  /  Fecha: 19/11/2041 (dos dias despues del incidente)\n\n[Este informe fue elaborado a partir de muestras de cabello del Dr. Borda\n guardadas en el archivo medico como parte del protocolo rutinario de higiene.]\n\nANALISIS DE CABELLO (cronologia de ultimas 3 semanas):\n  Semana 1 (01-07/11): Sin trazas de sustancias anormales.\n  Semana 2 (08-14/11): Presencia de compuesto organico no identificado (trazas).\n                       Compatible con alcaloide de origen marino.\n  Semana 3 (15-17/11): Concentracion del mismo compuesto x4 respecto a semana 2.\n                       Patron consistente con administracion diaria acumulativa.\n\nCONCLUSION:\n  El Dr. Borda fue envenenado de forma sistematica durante al menos 9-10 dias.\n  El compuesto es consistente con el agente B-9 del laboratorio de biologia.\n  La causa de muerte fisica no fue solo el envenenamiento:\n  el sujeto fue encerrado en la esclusa B en estado de debilidad severa.\n\n[Informe no enviado al informe oficial. Guardado en archivo medico local.]" },
          "autopsia_borda.enc": { type: "file", hidden: true, locked: true, password: "FORENSE", content: "INFORME DE AUTOPSIA — DR. ELIAS BORDA\nPreparado por: Comision de Investigacion Maritima Profunda (2058, 17 anos despues)\nA partir de restos conservados en la esclusa sellada.\n\nCAUSA DE MUERTE REAL:\n  Combinacion de intoxicacion cronica por agente neurotrofico marino\n  y muerte por descompresion brusca (exposicion al exterior de la esclusa B).\n\nHALLAZGOS OSEOS Y TISULARES:\n  Marcadores de intoxicacion en tejido oseo: positivo (alcaloide marino)\n  Lesiones por onda de presion: consistentes con apertura de esclusa en condiciones abisales\n\nCONCLUSION OFICIAL DE LA COMISION:\n  El Dr. Borda fue envenenado de forma premeditada durante varios dias\n  y posteriormente ejecutado mediante un mecanismo de esclusa manipulado.\n  Esto es un homicidio con premeditacion. No un accidente de presion.\n\nRESPONSABLE SEÑALADO:\n  Mara Voss (jefa de seguridad, Nereida-9, ciclo nov. 2041)\n  Detenida en 2058 gracias a este expediente de recuperacion." }
        }
      },
      personal: {
        type: "dir",
        children: {
          "ficha_borda.txt": { type: "file", content: "FICHA DE PERSONAL — DR. ELIAS BORDA\nCargo: Biologo Jefe / Investigador Principal\nNacimiento: 1990. Nacionalidad: española.\nFormacion: Doctorado en Farmacologia Marina, Universidad de Barcelona.\nPublicaciones: 34 articulos. Dos premios internacionales de investigacion abisal.\nAntiguedad en Nereida-9: desde la inauguracion (2034). 7 anos.\n\nNOTA DE RRHH:\n  'El Dr. Borda rechazo en octubre de 2041 firmar el acuerdo de cesion de derechos\n   sobre el agente B-9 a Solvang Corp. Lo hizo por escrito y con asistencia juridica.'\n\nNOTA DE CORPORACION (Solvang Corp, nivel ejecutivo):\n  'Borda es el unico obstaculo legal para la comercializacion de B-9.\n   Resolver antes del fin del ciclo 7.' [fecha: 05/11/2041]" },
          "ficha_kern.txt": { type: "file", content: "FICHA DE PERSONAL — LIA KERN\nCargo: Tecnico de Radio y Comunicaciones\nNacimiento: 2008. Nacionalidad: alemana.\nFormacion: Ingenieria de Telecomunicaciones (summa cum laude, Munich).\nAntiguedad en Nereida-9: 4 anos.\n\nNOTA DE EVALUACION (Raal, 2041):\n  'Kern es la mejor operadora de radio que hemos tenido. Hiperobservadora.\n   A veces su curiosidad me preocupa, pero en situaciones de crisis es invaluable.'" },
          "ficha_voss.txt": { type: "file", hidden: true, content: "FICHA DE PERSONAL — MARA VOSS\nCargo: Jefa de Seguridad\nNacimiento: 1997. Nacionalidad: suiza / alemana.\nFormacion: Seguridad corporativa (Meridian BioSec), operaciones en campo.\nAntiguedad en Nereida-9: 2 anos (contratacion directa por Solvang Corp, no por Nereida).\n\nHISTORIAL PREVIO:\n  2030-2039: Operaciones de campo para Meridian BioSec (filial de Solvang).\n  2039:      Investigada por desaparicion de testigo en caso de exportacion ilegal.\n             Caso archivado por falta de pruebas.\n  2039:      Contrato firmado bajo nombre anterior: Mara Eiden.\n\nNOTA DE RRHH (interna, Solvang Corp):\n  'Voss ha completado con exito cinco operaciones de recuperacion de activos biologicos.\n   Su historial la hace ideal para la situacion de Nereida-9.'" },
          "ficha_aram.txt": { type: "file", hidden: true, content: "FICHA DE PERSONAL — ING. NOEL ARAM\nCargo: Ingeniero de Sistemas e Infraestructura\nNacimiento: 2003. Nacionalidad: turca / francesa.\nFormacion: Ingenieria de Sistemas Autonomos, Paris-Saclay.\nAntiguedad en Nereida-9: 5 anos.\n\nNOTA DE EVALUACION (Raal, 2040):\n  'Aram es mi mejor tecnico. Paranoidamente documentador: guarda copias de todo.\n   Si algo falla en esta estacion, Noel lo encontrara antes que el sistema automatico.'\n\nNOTA MANUSCRITA DE KERN (pegada a la ficha):\n  'Si encuentran a Noel despues de que todo esto se limpie,\n   recordad que el no abrio esa puerta por voluntad propia.\n   Le obligaron. Eso lo se porque conozco a Noel.'" },
          "contrato_voss.enc": { type: "file", hidden: true, locked: true, password: "EIDEN", content: "CONTRATO DE SERVICIOS ESPECIALES — RECUPERACION DE ACTIVOS\nSolvang Asset Trust / Meridian BioSec Security Division\n\nCONTRATISTA: Mara Eiden (alias operativo: Voss)\nCLIENTE: Solvang Asset Trust\nOBJETO: Recuperacion del activo biologico B-9 (Nereidina-9) de la estacion Nereida-9.\n\nOBLIGACIONES DEL CONTRATISTA:\n  1. Establecer un canal de exportacion de datos y muestras fisicas (alias: VANTA).\n  2. Neutralizar cualquier obstaculo legal o personal a dicha exportacion.\n  3. Garantizar que la operacion no deje rastro documental en los sistemas de la estacion.\n  4. En caso de exposicion inminente, activar el protocolo de cierre limpio.\n\nRETRIBUCION:\n  500.000 CHF por la exportacion completa del agente B-9.\n  Prima de 150.000 CHF adicionales por resolucion completa sin rastro legal.\n\nFIRMA: Mara Eiden — fecha: 03/09/2041\nFIRMA CORPORACION: [redactado]\n\nNOTA: Este contrato establece el motivo economico del asesinato de Borda, Aram y Tellez." }
        }
      },
      comunicaciones: {
        type: "dir",
        children: {
          "radiograma_entrada.txt": { type: "file", content: "RADIOGRAMA ENTRANTE — 16/11/2041 / 18:43 UTC\nOrigen: Centro de Operaciones Solvang Corp\nDestino: Estacion Nereida-9 / Cmd. Ivo Raal\n\n'Comandante Raal:\n\nHemos recibido su solicitud de revision del protocolo del Dr. Borda.\nLe informamos que el ciclo de operaciones 7 se cierra a las 24:00 del 17 de noviembre.\nTodos los activos biologicos del laboratorio deben ser transferidos al equipo\nde relevo segun el protocolo estandar de fin de ciclo.\n\nSolvang Corp agradece la dedicacion de toda la tripulacion.\nEl equipo de relevo llegara el 18 de noviembre a las 10:00.'\n\nNOTA MANUSCRITA DE RAAL (al margen del impreso):\n  'Me mandaron a Voss en lugar de un equipo medico.\n   Y el equipo de relevo llega el dia DESPUES del fin de ciclo.\n   Alguien queria que todo terminara antes de que llegara nadie.'" },
          "mensajes_borrados.enc": { type: "file", hidden: true, locked: true, password: "VANTA", content: "RECUPERACION DE MENSAJES BORRADOS — TERMINAL SEGURIDAD\nRecuperados del buffer de escritura del disco de Voss\n\n[Mensaje 1 — 15/11 — 23:41]\nDE: m_voss@n9sec\nPARA: vanta-relay-07@[cifrado]\n'Cuarta exportacion completada. Total: 6.1 GB de datos B-9.\nBorda ha descubierto la sustraccion de muestras. Hay que acelerar.\nActivando protocolo de cierre al final del ciclo 7. Confirmar recepcion.'\n\n[Respuesta — 15/11 — 23:59]\n'Confirmado. Procede con el protocolo de cierre limpio.\nNecesitamos los tres neutralizados: Borda, Aram y Tellez.\nLa chica de radio no importa: no sabe nada concreto.\nRaal estara en contencion y no podra interferir.'\n\n[Mensaje 2 — 17/11 — 03:28]\nDE: m_voss@n9sec\nPARA: vanta-relay-07@[cifrado]\n'Protocolo completado. Los tres han salido por la esclusa B.\nRaal en contencion. Kern en la cabina sin acceso exterior.\nMe voy en el siguiente transporte. Borrado de logs iniciado.'\n\n[FIN DE RECUPERACION — algunos bloques siguen cifrados]" },
          "intercepcion_corporativa.txt": { type: "file", hidden: true, content: "INTERCEPCION DE COMUNICACION CORPORATIVA\nCapturada por: Comision de Investigacion Maritima, 2058\nOrigen: Archivos internos Solvang Corp / Meridian BioSec\n\nCORREO INTERNO — NIVEL EJECUTIVO — 01/11/2041:\nDE: Consejo Ejecutivo, Solvang Corp\nPARA: Meridian BioSec, Responsable de Operaciones\n\n'El activo Nereidina-9 (B-9) tiene un valor estimado de mercado no regulado\nde entre 800 millones y 1.200 millones de dolares en el sector de defensa biologica.\n\nEl Dr. Borda es el unico propietario legal del descubrimiento.\nSu negativa a ceder los derechos en octubre es un obstaculo inaceptable.\n\nSe autoriza la operacion EIDEN con plena cobertura corporativa.\nMara Eiden ha sido activada en la estacion bajo cobertura de jefa de seguridad.\nSe espera resolucion completa antes del cierre del ciclo 7 (17/11).\n\nEste correo es autoborrable en 72 horas. Copia en sobre cerrado en sede central.'\n\n[NOTA DEL FISCAL: Este correo fue recuperado de un servidor de respaldo que Solvang\nno sabia que existia. Fue la clave para procesar a los directivos de la corporacion.]" }
        }
      },
      legal: {
        type: "dir",
        children: {
          "legal_sira_audio.transcript": { type: "file", hidden: true, content: "[Grabacion de audio — Sira Tellez — 17/11/2041 — 02:30]\n[Encontrada en el modulo de comunicaciones legales, sin fecha de borrado]\n\nVoz (Sira Tellez): Si este registro aparece, significa que ya me encontraron.\n\n[Pausa de 4 segundos]\n\nVoz: He cruzado los contratos de aprovisionamiento con los accesos biometricos de seguridad.\nEl alias VANTA aparece en cuatro transferencias de datos salientes en los ultimos 7 dias.\nCada transferencia coincide en hora y dia con los accesos de m_voss al puerto RK-44.\n\nVoz: El apellido de soltera de Mara Voss aparece en los contratos mas antiguos que encontre.\nLo firmo con su nombre anterior: Eiden. Mara Eiden.\nEsa firma conecta todos los documentos con la misma persona.\n\nVoz: Tenia los contratos impresos en mi modulo. Esta tarde desaparecieron.\nVoss entro mientras yo estaba en el comedor. La vi salir cuando regresaba.\n\n[Ruido estatico de 6 segundos]\n\nVoz: Noel me pidio que fuera a la esclusa B esta noche a las 03:00.\n     Dice que tiene algo que mostrarme en el sistema de la esclusa.\n     No me gusta ese plan, pero Noel no me pediria algo asi sin una razon.\n     Si no regreso, buscad el nombre EIDEN en todos los archivos.\n     Ese nombre es la llave.\n\n[Audio termina abruptamente 02:49]" }
        }
      },
      private: {
        type: "dir",
        children: {
          "veredicto_final.evd": { type: "file", locked: true, password: "EIDEN", content: "VEREDICTO FINAL — CASO NEREIDA-9\nComision de Investigacion Maritima Profunda\nFecha de cierre: 14 de marzo de 2058 (17 anos despues de los hechos)\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nRESPONSABLE PRINCIPAL: Mara Voss (nombre real: Mara Eiden)\nJefa de Seguridad, Estacion Nereida-9, ciclo noviembre 2041\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nVICTIMAS:\n  Dr. Elias Borda    — Biologo jefe. Envenenado sistematicamente. Ejecutado en esclusa B.\n  Ing. Noel Aram     — Ingeniero de sistemas. Coercionado para abrir la esclusa. Ejecutado.\n  Sira Tellez        — Analista juridica. Ejecutada en esclusa B.\n\nMOTIVO:\n  Voss fue contratada por Solvang Corp / Meridian BioSec bajo el alias de operacion EIDEN\n  para extraer el agente biologico B-9 (Nereidina-9) de la estacion Nereida-9\n  y eliminar cualquier obstaculo legal a su comercializacion.\n  El Dr. Borda habia rechazado ceder los derechos del descubrimiento.\n  Aram y Tellez habian descubierto la operacion por separado.\n\nMETODO:\n  Borda: envenenamiento acumulativo mediante agente B-9 en bebidas. Varios dias.\n  Los tres: encierro en la esclusa B usando el protocolo MAREA NUEVE de forma ilicita.\n            Apertura de la compuerta exterior. Presion abisal instantanea.\n  Raal: confinado en modulo de contencion mediante protocolo activado desde el puesto de Voss.\n  Kern: aislada en cabina de radio. No fue eliminada porque 'no sabia nada concreto'.\n\nPRUEBAS DETERMINANTES:\n  1. Contrato EIDEN (firmado bajo nombre real de Voss con Solvang/Meridian)\n  2. Grabacion de audio de Sira Tellez (menciona alias EIDEN como clave)\n  3. Dump de red RK-44 (patron de accesos m_voss con codigo VANTA)\n  4. Mensajes borrados recuperados del terminal de Voss\n  5. Informe toxicologico de F. Adis (envenenamiento cronica confirmado)\n  6. Bitacora de Noel Aram (relay + codigo RK-44 + alias VANTA)\n  7. Intercepcion corporativa (autorizacion de Solvang para la operacion)\n\nSENTENCIA:\n  Mara Voss: cadena perpetua. Detenida en Buenos Aires en 2057.\n  Directivos de Solvang Corp: procesados por complicidad. Penas de 15 a 25 anos.\n  La empresa Solvang fue disucelta por orden judicial en 2059.\n\nEXPEDIENTE CERRADO." }
        }
      }
    }
  },
  databases: {
    protocolos: {
      marea9: { text: "PROTOCOLO MAREA NUEVE localizado en logs de esclusa. Nuevos archivos revelados.", reveal: ["/ops/reporte_esclusa.log", "/ops/bitacora_noel.txt"] },
      exportacion: { text: "Manifiesto de carga del ciclo recuperado. Exportaciones sin firma identificadas.", reveal: ["/ops/manifiesto_carga.txt"] }
    },
    turnos: {
      "0317": { text: "Anomalia en registro de turno a las 03:17 confirmada. Bitacora de Aram y reporte de esclusa accesibles.", reveal: ["/ops/reporte_esclusa.log", "/ops/bitacora_noel.txt"] }
    },
    finanzas: {
      vanta: { text: "Alias VANTA identificado en red interna. Audio de Tellez y volcado de red accesibles.", reveal: ["/legal/legal_sira_audio.transcript", "/ops/red_nucleo.enc"] },
      eiden: { text: "Nombre EIDEN rastreado en archivos de personal. Contrato cifrado de Voss accesible.", reveal: ["/personal/contrato_voss.enc"] }
    },
    biologia: {
      borda: { text: "Notas de campo de Kern y reporte de muestras B-9 recuperados.", reveal: ["/bio/nota_kern_observaciones.txt", "/bio/informe_muestras_b9.txt"] },
      muestras: { text: "Informe completo de sustraccion de muestras disponible. Registro del experimento accesible.", reveal: ["/bio/informe_muestras_b9.txt", "/bio/registro_experimento.txt"] },
      experimento: { text: "Registro de investigacion B-9 con notas personales de Borda encontrado.", reveal: ["/bio/registro_experimento.txt"] },
      agente: { text: "Ficha tecnica clasificada del agente B-9 accesible (cifrada).", reveal: ["/bio/ficha_agente_b9.enc"] }
    },
    medico: {
      borda: { text: "Historial medico del Dr. Borda de noviembre 2041 recuperado.", reveal: ["/medico/historial_borda.txt"] },
      autopsia: { text: "Informe de autopsia de la Comision de 2058 accesible (cifrado).", reveal: ["/medico/autopsia_borda.enc"] },
      alcaloide: { text: "Informe toxicologico de F. Adis recuperado. Envenenamiento confirmado.", reveal: ["/medico/toxicologia.txt"] }
    },
    seguridad: {
      biometria: { text: "Log de accesos biometricos de la semana del incidente recuperado.", reveal: ["/logs/accesos_biometricos.log"] },
      camaras: { text: "Log de incidencias de camaras con patron de apagados recuperado.", reveal: ["/logs/camaras_offline.log"] }
    },
    personal: {
      voss: { text: "Ficha de personal de Mara Voss con historial corporativo previo accesible.", reveal: ["/personal/ficha_voss.txt"] },
      aram: { text: "Ficha de personal de Noel Aram recuperada.", reveal: ["/personal/ficha_aram.txt"] }
    },
    comunicaciones: {
      eliminados: { text: "Mensajes borrados del terminal de Voss parcialmente recuperados (cifrados).", reveal: ["/comunicaciones/mensajes_borrados.enc"] },
      corporacion: { text: "Intercepcion de comunicacion interna de Solvang Corp recuperada.", reveal: ["/comunicaciones/intercepcion_corporativa.txt"] },
      raal: { text: "Grabacion interceptada de comunicacion del Comandante Raal accesible (cifrada).", reveal: ["/audio/audio_raal_interceptado.enc"] }
    },
    audio: {
      kern3: { text: "Tercer audio de Kern (18/11) con detalles del comportamiento de Voss recuperado.", reveal: ["/audio/audio_kern_03.transcript"] }
    }
  }
};
