// CASO 1 — ECOS BAJO CUARENTENA
var CASE1 = {
  title: "Ecos Bajo Cuarentena",
  year: "2041",
  setting: "Estación oceanográfica abisal Nereida-9",
  tagline: "Tres muertes. Una red de tráfico biológico. Un apagón que borró las pruebas.",
  intro: "Has accedido a la terminal de recuperación de la estación Nereida-9.\nFue sellada el 17 de noviembre de 2041 tras un \"accidente de presión\".\nTres de sus seis tripulantes figuran como bajas. Ningún informe oficial los menciona por nombre.\n\nEl sistema fue parcialmente borrado. Estas son las copias que sobrevivieron.\nLee los archivos. Sigue las pistas. Descubre quién mató a Borda, Aram y Tellez.",
  solveFile: "veredicto_final.evd",
  startFiles: [
    "/boot_notice.txt",
    "/audio/radio_emergencia_041.transcript",
    "/audio/audio_kern_02.transcript",
    "/logs/comedor_memo_77.txt",
    "/logs/turno_seguridad.log",
    "/personal/ficha_borda.txt",
    "/personal/ficha_kern.txt",
    "/comunicaciones/radiograma_entrada.txt",
    "/private/veredicto_final.evd"
  ],
  hints: [
    "Empieza con 'ls' en la raíz y lee boot_notice.txt para orientarte. Luego 'cd audio' y lee las transcripciones.",
    "En radio_emergencia_041, Kern menciona el apodo del pez del Dr. Borda. Ese apodo es la primera contraseña.",
    "cd audio → unlock audio_borda_01.enc FARO — El audio de Borda menciona el protocolo MAREA NUEVE.",
    "Usa 'examine 0317' para entender la anomalía del reloj maestro. Ese minuto borrado es la prueba de manipulación.",
    "Usa 'examine marea9' para entender cómo se usó el protocolo de emergencia de forma criminal.",
    "Usa 'cd logs' y lee turno_seguridad.log. Voss tuvo una ausencia de 25 minutos sin justificar con la cámara apagada.",
    "Usa 'examine biometria' para cruzar los movimientos de toda la tripulación la noche del 17/11.",
    "Usa 'cd personal' y lee la ficha de Voss. Fue contratada directamente por Solvang, no por la estación.",
    "Usa 'examine corporacion' para entender el papel de Solvang Corp y por qué querían el agente B-9 a cualquier precio.",
    "Usa 'search biologia muestras' para revelar el informe de sustracción de las muestras B-9 firmadas por m_voss.",
    "Usa 'examine taza' para entender cómo envenenaron a Borda. Luego 'examine alcaloide' para ver qué tipo de veneno usaron.",
    "Usa 'search medico borda' para ver su historial. Alguien le negó el análisis toxicológico la noche del 16/11.",
    "Usa 'search protocolos marea9' para revelar el reporte de esclusa y la bitácora de Noel.",
    "Usa 'examine relay' para entender cómo Voss suplantó las credenciales de Aram. Luego 'examine rk44'.",
    "Usa 'cd ops' → unlock red_nucleo.enc RK44 para ver el historial completo de accesos al puerto oculto con nombres reales.",
    "La bitácora de Noel menciona el código RK-44 y el alias VANTA. Usa 'search finanzas vanta'.",
    "Usa 'cd comunicaciones' → unlock mensajes_borrados.enc VANTA para leer las órdenes directas que recibió Voss desde fuera.",
    "Usa 'search protocolos exportacion' para ver el manifiesto de carga con los bultos sin firma del Dr. Borda.",
    "El audio de Tellez revela el alias de operación de Voss: EIDEN. Busca también 'search personal voss'.",
    "Usa 'examine voss' y 'profile voss' para armar el perfil completo. Luego cd private → unlock veredicto_final.evd EIDEN.",
    "Usa 'profile kern' y 'profile raal' para entender por qué los supervivientes no pudieron evitar el crimen.",
    "Usa 'cd comunicaciones' y lee intercepcion_corporativa.txt. Ese correo fue la clave para procesar a los directivos de Solvang.",
    "Usa 'timeline' para ver la cronología completa. Los accesos nocturnos de Voss al puerto RK-44 siguen un patrón exacto.",
    "Comandos extra: map, timeline, evidence, profile [nombre], examine [término]."
  ],
  map: "NEREIDA-9 — PLANTA PRINCIPAL (NIVEL 3)\n" +
    "Profundidad: 2.847 metros\n" +
    "═══════════════════════════════════════════════════\n" +
    "  ┌──────────┐  ┌──────────┐  ┌─────────────────┐\n" +
    "  │  MANDO   │  │  RADIO   │  │  LAB. BIOLOGIA  │\n" +
    "  └────┬─────┘  └────┬─────┘  └────────┬────────┘\n" +
    "       └─────────────┴────────────────┬─┘\n" +
    "  ┌────────────────────────────────────┴──────────┐\n" +
    "  │                PASILLO CENTRAL B              │\n" +
    "  └──────┬─────────────────────┬──────────────────┘\n" +
    "         │                     │\n" +
    "  ┌──────┴──────┐     ┌────────┴────────┐\n" +
    "  │   COMEDOR   │     │   ESCLUSA B  ←→ MAR │\n" +
    "  └─────────────┘     └─────────────────────┘\n" +
    "  ┌──────────┐  ┌──────────┐  ┌──────────┐\n" +
    "  │  MEDICO  │  │PERSONAL  │  │  OPS /   │\n" +
    "  │          │  │          │  │ SISTEMAS │\n" +
    "  └──────────┘  └──────────┘  └──────────┘\n" +
    "  ┌──────────┐  ┌──────────────────────────┐\n" +
    "  │  LEGAL   │  │ PRIVATE (acceso restringido)│\n" +
    "  └──────────┘  └──────────────────────────┘",
  profiles: {
    borda: "DR. ELÍAS BORDA — Biólogo Jefe\nEdad: 51. Especialidad: química marina y farmacología de profundidades.\nAntigüedad en Nereida-9: 7 años (desde la inauguración).\nCarácter: meticuloso, desconfiado de los cambios de protocolo. Guardaba registros de audio de todo.\nSituación: fallecido el 17/11/2041. Causa oficial no especificada. Causa real: investigar.\nConexión clave: descubrió el robo de muestras B-9 y lo confrontó directamente con Voss.",
    voss: "MARA VOSS — Jefa de Seguridad\nEdad: 44. Formación: ex-corporativa en Meridian BioSec (filial de Solvang Corp).\nAntigüedad en Nereida-9: 2 años (contratada directamente por la corporación).\nCarácter: eficiente, hermética, no socializa con el resto de la tripulación.\nSituación: ausencia injustificada de 25 min el 17/11. Cámara offline en ese intervalo.\nConexión clave: accesos nocturnos regulares al puerto RK-44. Alias de operación: EIDEN.",
    kern: "LIA KERN — Técnico de Radio y Comunicaciones\nEdad: 33. Especialidad: telecomunicaciones subacuáticas y sistemas de emergencia.\nAntigüedad en Nereida-9: 4 años.\nCarácter: observadora, muy apegada al Dr. Borda (relación de mentor/alumna).\nSituación: superviviente. Estuvo en la cabina de radio cuando ocurrió el incidente.\nConexión clave: única testigo directa del comportamiento de Voss antes de la muerte de Borda.",
    aram: "NOEL ARAM — Ingeniero de Sistemas\nEdad: 38. Especialidad: redes internas y sistemas de presión.\nAntigüedad en Nereida-9: 5 años.\nCarácter: analítico, poco sociable. Documentaba todo en bitácoras manuscritas.\nSituación: fallecido el 17/11/2041. Según su propia nota, fue obligado a abrir la esclusa.\nConexión clave: descubrió el puerto RK-44 y el código de salida VANTA antes de morir.",
    tellez: "SIRA TELLEZ — Analista Jurídica\nEdad: 29. Especialidad: cumplimiento normativo y auditoría de contratos.\nAntigüedad en Nereida-9: 1 año (contratada para auditar operaciones internas).\nCarácter: discreta, pero muy persistente con los números. Guardaba copias de todo.\nSituación: fallecida el 17/11/2041. Había rastreado el flujo financiero hasta el alias Eiden.\nConexión clave: su grabación de audio es la que vincula directamente a Voss con la operación.",
    raal: "CMD. IVO RAAL — Comandante de Estación\nEdad: 58. Formación: marina mercante y gestión de instalaciones offshore.\nAntigüedad en Nereida-9: 7 años.\nCarácter: formal, por-el-libro, pero protector de su tripulación.\nSituación: superviviente. Fue encerrado en módulo de contención por protocolo durante el incidente.\nConexión clave: dejó la nota de boot_notice.txt. Sospechaba que el informe oficial era falso."
  },
  examine: {
    taza: "La taza de cerámica azul del Dr. Borda. Siempre café sin azúcar, según los registros del comedor.\nEsa noche la taza fue encontrada rota en la bandeja técnica a las 01:10.\nEl memo del comedor indica que olía diferente a café normal.\nUn alcaloide vegetal en bebida caliente sería casi indetectable al gusto.",
    esclusa: "La Esclusa B es la única compuerta de acceso directo al exterior de la estación.\nEstá ubicada al final del Pasillo B, entre el comedor y el laboratorio de biología.\nOpera en dos modos: automático (gestión central) y manual (requiere autorización de dos operadores).\nEl evento del 17/11 a las 03:17 carece de firma digital — lo que es técnicamente imposible en modo normal.",
    "b9": "Agente biológico experimental catalogado en el laboratorio de biología de Nereida-9.\nClasificación: neurotrófico marino de origen abisal — aún sin nombre comercial.\nFue descubierto por el Dr. Borda en 2039 en las muestras del zanjón de Nereida.\nValor estimado en el mercado farmacéutico no regulado: desconocido, pero extremadamente alto.\nEl volumen de las muestras bajó un 41% sin justificación entre el 13 y el 15 de noviembre.",
    alcaloide: "Compuesto químico de origen vegetal (o sintético derivado) con efectos sobre el sistema nervioso.\nEn dosis acumulativas pequeñas durante tres o cuatro días puede simular insuficiencia cardíaca.\nEl Dr. Borda, siendo farmacólogo, reconoció el patrón en su propia sintomatología.\nEl compuesto más probable: derivado de aconitina o cicutoxina, solubles en agua caliente.",
    vanta: "Alias de operación utilizado en todas las transferencias financieras irregulares rastreadas por Noel Aram.\nApunta a una cuenta offshore sin titular identificado.\nEste alias conecta el puerto de red RK-44 con movimientos de fondos exteriores a la estación.\nEl nombre de la cuenta corporativa de respaldo era Solvang Asset Trust.",
    raal: "El Comandante Raal fue el primero en sospechar del informe oficial.\nDurante el incidente estuvo encerrado en el módulo de contención — protocolo de emergencia activado automáticamente.\nEste protocolo solo puede activarse desde el puesto de control de seguridad. Es decir, desde el puesto de Voss.\nSu nota en boot_notice.txt fue redactada desde un terminal de respaldo sin conexión a la red principal.",
    relay: "Dispositivo de comunicación de red de baja frecuencia usado para acceder a puertos de respaldo.\nNoel Aram descubrió uno conectado al bus de datos de su terminal el 13 de noviembre.\nEste tipo de relay permite suplantar credenciales de usuario sin dejar huella en el log principal.\nEs el método mediante el cual alguien accedió al puerto RK-44 bajo el nombre de usuario n9_sec.",
    "0317": "La marca de tiempo 03:17 del 17 de noviembre no existe en el reloj maestro de la estación.\nNoel Aram explica en su bitácora que esto es posible usando un paquete de autorización duplicado.\nEn la práctica significa que alguien borró esos 60 segundos del historial oficial.\nEl reporte de la esclusa lo llama 'evento huérfano': un evento sin firma digital registrada.",
    borda: "El Dr. Elías Borda era la persona con mayor conocimiento científico de la estación.\nDescubrió el robo de muestras B-9 el 15 de noviembre. Lo confrontó con Voss directamente.\nSabía que estaban envenenándole pero no podía probarlo sin un análisis de sangre completo.\nGrababa registros de audio privados usando el nombre de su pez mascota como contraseña: FARO.",
    voss: "Mara Voss llegó a Nereida-9 contratada directamente por la corporación, saltándose el proceso interno.\nSu contrato original estaba firmado bajo el alias operativo EIDEN.\nTenía acceso permanente al puesto de control de seguridad y al sistema de esclusa.\nSus accesos nocturnos al puerto RK-44 siguieron un patrón exacto: siempre entre las 03:00 y las 03:05.",
    noel: "Noel Aram era el único que podía entender realmente cómo habían manipulado la red de la estación.\nDescubrió el relay en su terminal y lo documentó en su bitácora antes de ser neutralizado.\nSu nota al margen del reporte de la esclusa dice 'Me obligaron'. Fue amenazado para abrir la compuerta.\nMurió junto con Borda y Tellez en la esclusa B.",
    kern: "Lia Kern fue la primera en levantar la voz sobre la muerte de Borda.\nIntentó contactar a Raal cinco veces sin éxito. El comandante estaba en contención.\nSu observación más importante: Voss fue la primera en limpiar el espacio de Borda antes de que llegara nadie.\nSu tercer audio (kern_03) contiene detalles sobre el comportamiento de Voss en las 48 horas previas.",
    tellez: "Sira Tellez había rastreado el flujo financiero usando solo los documentos legales de la estación.\nDescubrió que el alias EIDEN aparecía en contratos firmados antes de que Voss llegara a Nereida-9.\nSu grabación de audio es la prueba más directa del vínculo entre Voss y la operación VANTA.\nFue a la esclusa B esa noche porque Noel le había pedido ayuda para documentar lo que había encontrado.",
    eiden: "Nombre utilizado por Mara Voss como alias de operación antes de su contratación en Nereida-9.\nAparece en contratos firmados en Marsella (2038-2039) para exportación de material biológico no regulado.\nEs también el apellido de soltera que Voss usaba en sus documentos previos a la boda.\nEl contrato en /personal/contrato_voss.enc está firmado bajo ese nombre.",
    faro: "El nombre del pez ciego del Dr. Borda. Un pez de las profundidades sin pigmentación.\nBorda lo usaba como metáfora: 'un faro cuando todo se va al fondo'.\nEra también la contraseña de sus registros de audio privados.\nLia Kern lo menciona en la primera transcripción de radio de emergencia.",
    marea9: "Nombre del protocolo de contingencia de la esclusa B.\nPermite cambiar la esclusa a modo manual desde un terminal de movilidad sin autorización doble.\nEste protocolo existe para emergencias reales. Fue usado de forma criminalmente incorrecta el 17/11.\nSolo el personal de seguridad conocía su nombre y procedimiento de activación.",
    rk44: "Código del puerto de red de respaldo de Nereida-9.\nPermite acceso externo al bus de datos de la estación saltando los logs principales.\nSolo lo conocían el Dr. Borda (en calidad de investigador principal) y Noel Aram (sistemas).\nVoss lo obtuvo robando el terminal de Aram mediante un relay instalado subrepticiamente.",
    nereida: "La estación Nereida-9 fue construida en 2034 por el consorcio Solvang Corp / Marina Profunda SA.\nSe ubica en la fosa abisopelágica de Nereida, frente a las islas Canarias orientales.\nFue diseñada para investigación biológica y geológica en profundidades superiores a 2.000 metros.\nSus tres módulos de vida pueden sellarse de forma independiente en caso de emergencia.",
    biometria: "El sistema biométrico de Nereida-9 registra el movimiento de todos los tripulantes mediante sensores.\nLa última lectura del Dr. Borda fue a las 23:58 en el pasillo de biología, según el log.\nNoel Aram desaparece del registro biométrico a las 03:09 — 8 minutos antes del evento huérfano.\nLia Kern aparece en la cabina de radio sin interrupción desde las 22:00 hasta las 07:00.",
    manifiesto: "El manifiesto de carga de Nereida-9 lista los suministros y exportaciones de cada ciclo.\nEn el ciclo de octubre-noviembre 2041, hay tres bultos marcados 'muestra biológica Cód. NTX' sin firma de autorización del biólogo jefe.\nEl Dr. Borda era el único con autoridad para firmar exportaciones biológicas. Él nunca firmó esos bultos.",
    corporacion: "Solvang Corp es la empresa matriz que financiaba las operaciones de Nereida-9.\nSu filial de seguridad (Meridian BioSec) fue la que contrató directamente a Mara Voss.\nVoss recibía instrucciones paralelas de Meridian BioSec al margen del canal oficial de la estación.\nLa intercepción corporativa en /comunicaciones/ contiene una de esas instrucciones."
  },
  timeline: [
    { time: "10/11  03:02", event: "Primer acceso nocturno de m_voss al puerto RK-44 (exportación VANTA)", trigger: "/ops/red_nucleo.enc" },
    { time: "12/11  02:58", event: "Segundo acceso de m_voss al puerto RK-44", trigger: "/ops/red_nucleo.enc" },
    { time: "13/11  ~18:00", event: "Noel Aram descubre un relay en su terminal. Lo documenta en su bitácora.", trigger: "/ops/bitacora_noel.txt" },
    { time: "14/11  03:00", event: "Tercer acceso de m_voss al puerto RK-44", trigger: "/ops/red_nucleo.enc" },
    { time: "15/11  02:30", event: "Voss accede al laboratorio de biología sin autorización. Kern lo atestigua.", trigger: "/bio/nota_kern_observaciones.txt" },
    { time: "15/11  ~16:00", event: "Borda detecta la sustracción de 185 ml de muestra B-9. Último acceso firmado: m_voss.", trigger: "/bio/informe_muestras_b9.txt" },
    { time: "15/11  noche", event: "Borda comienza a detectar trazas de alcaloide en sus bebidas. Inicia registros de audio.", trigger: "/audio/audio_borda_01.enc" },
    { time: "16/11  03:00", event: "Cuarto acceso de m_voss al puerto RK-44", trigger: "/ops/red_nucleo.enc" },
    { time: "16/11  ~20:00", event: "Borda confronta a Voss. Llama a Kern esa noche: 'Si no te llamo mañana, busca mi pez'.", trigger: "/bio/nota_kern_observaciones.txt" },
    { time: "17/11  22:10", event: "Borda consume café en el comedor. Voss solicitó cierre de la máquina norte sin formulario.", trigger: "/logs/comedor_memo_77.txt" },
    { time: "17/11  00:05", event: "Voss abandona el puesto de control sin justificación (25 minutos). Cámara offline.", trigger: "/logs/turno_seguridad.log" },
    { time: "17/11  00:32", event: "Voss regresa y notifica 'sin novedad' al comandante Raal.", trigger: "/logs/turno_seguridad.log" },
    { time: "17/11  02:58", event: "Inicio de secuencia en Esclusa B. Usuario: n9_sec (suplantación con relay).", trigger: "/ops/reporte_esclusa.log" },
    { time: "17/11  03:17", event: "EVENTO HUÉRFANO: esclusa abierta. Noel obligado. Borda, Aram y Tellez: fallecidos.", trigger: "/ops/reporte_esclusa.log" },
    { time: "17/11  09:15", event: "Raal descubre los cuerpos. Activa sellado de emergencia. Primer comunicado oficial.", trigger: "/boot_notice.txt" }
  ],
  filesystem: {
    type: "dir",
    children: {
      "boot_notice.txt": { type: "file", content: "NEREIDA-9 / TERMINAL DE RECUPERACIÓN\nSesión restaurada desde respaldo parcial — integridad: 62%\nFecha de sellado: 17 de noviembre de 2041\n\nTRIPULACIÓN ASIGNADA (ciclo nov. 2041):\n  Dr. Elías Borda     — Biólogo jefe\n  Ing. Noel Aram      — Sistemas / Infraestructura\n  Lia Kern            — Técnico radio y comunicaciones\n  Sira Tellez         — Analista jurídica\n  Mara Voss           — Jefa de seguridad\n  Cmd. Ivo Raal       — Comandante\n\nESTADO DE MÓDULOS:\n  Módulo A (Mando / Radio):      SELLADO\n  Módulo B (Biología / Médico):  SELLADO\n  Módulo C (Ops / Legal):        SELLADO\n  Esclusa B:                     BLOQUEADA (post-evento)\n\nNota del administrador (Ivo Raal, terminal de respaldo):\n'No confíes en los reportes de incidente enviados a la corporación.\nTres de mis seis tripulantes no aparecen en ningún informe oficial.\nLos audios tienen más verdad que los formularios.\nSi alguien llega hasta aquí, que sepa que esto no fue un accidente.'\n\nDirectorios: /audio  /logs  /ops  /bio  /medico  /personal  /comunicaciones  /legal  /private\nComandos: help, ls, cd, read, unlock, search, examine, profile, timeline, evidence, map, hint, clear, menu" },
      audio: {
        type: "dir",
        children: {
          "radio_emergencia_041.transcript": { type: "file", content: "[Transcripción de audio — Radio Interna — 17/11/2041]\n[Audio inicia 00:03]\n\nVoz 1 (Lia Kern): Central, aquí Radio Interna. No tengo visual de Borda en enfermería.\nVoz 2 (Control): Confirmado. Última lectura biométrica a las 23:58 en pasillo de biología.\n\n[Ruido metálico lejano]\n\nVoz 1: Oí de nuevo ese golpe en la esclusa. No debería haber nadie ahí a esta hora.\nVoz 2: Manténte en cabina. No abras la puerta bajo ningún concepto.\n\n[Audio salta. Marca 00:49]\n\nVoz 1: El doctor siempre se reía de mis supersticiones.\n       Decía que su pez ciego era su faro cuando todo se iba al fondo.\n       Lo llamaba FARO. Una especie sin ojos que vive en la oscuridad total.\n       Cuando todo sea oscuro, busca a FARO, me dijo una vez.\nVoz 2: Lia, repite esa última parte.\nVoz 1: Que su mascota se llamaba igual que una luz para barcos. Eso es todo.\n\n[Interferencia larga — 38 segundos]\n\nVoz 1 (susurrando): Si alguien revisa este archivo después...\n                    busquen el registro privado de Borda. Él sabía lo que pasaba.\n\n[Audio termina 01:12]" },
          "audio_kern_02.transcript": { type: "file", content: "[Transcripción de audio — Cabina de Radio — 17/11/2041]\n[Audio inicia 14:20 — día siguiente al incidente]\n\nVoz (Lia Kern): He intentado cinco veces contactar con el comandante Raal.\nVoz (técnico guardia): El comandante está en módulo de contención por protocolo.\nVoz (Kern): Alguien activó ese protocolo de contención. Eso no ocurre solo.\n            Y ocurrió justamente cuando Raal quería ir a la esclusa.\n\nVoz (técnico): La señora Voss dijo que fue estrés prolongado en los tres técnicos.\nVoz (Kern): El Dr. Borda no estaba estresado. Estaba envenenado. Yo lo vi.\n            Vi la taza cuando limpiaron su módulo. Olía diferente al café normal.\n            Era algo amargo, químico. No me lo pude sacar de la nariz.\n\nVoz (técnico): La señora Voss fue la que reportó el incidente.\nVoz (Kern): Y fue también la primera en entrar al módulo de Borda antes de que llegara nadie.\n            El cuaderno de apuntes de Elías había desaparecido cuando entré yo.\n\n[Interferencia de 12 segundos]\n\nVoz (Kern): Si algo me pasa, mis notas están en /bio. Todas.\n            El jefe de seguridad ES el problema. No el estrés. Ella.\n\n[Audio cortado 14:41]" },
          "audio_kern_03.transcript": { type: "file", hidden: true, content: "[Transcripción de audio — Cabina de Radio — 18/11/2041]\n[Audio inicia 09:15 — segundo día tras el incidente]\n\nVoz (Lia Kern): Esto es para el registro. Por si alguien lo necesita después.\n\nEl jueves por la noche (16/11), antes de que ocurriera todo,\nvi a la señora Voss en el pasillo B a las 23:30 con una bolsa de mano pequeña.\nEsa bolsa no formaba parte de ningún equipo de seguridad que yo reconociera.\n\nEl viernes (17/11) a las 01:15 noté que la luz del módulo del Dr. Borda estaba encendida.\nEso era muy inusual. Él siempre la apagaba antes de medianoche.\nLlamé a la puerta. No respondió. No forcé la entrada porque no quise romper protocolo.\n\nMedia hora después vi a Voss salir del pasillo B. Sin la bolsa.\nLe pregunté si había visto al Dr. Borda. Me dijo que descansaba.\nSus manos temblaban ligeramente.\n\nEsa fue la última vez que hablé con ella antes de que todo se cerrara.\n\n[Silencio de 8 segundos]\n\nVoz (Kern): Cuiden a Ivo. Él sabe más de lo que ha podido decir.\n\n[Audio termina 09:44]" },
          "audio_borda_01.enc": { type: "file", locked: true, password: "FARO", content: "[Registro de audio privado — Dr. Elías Borda — 15/11/2041]\n[Audio inicia 00:07]\n\nVoz (Dr. Elías Borda): Registro privado. Si algo me sucede, este archivo es la prueba.\n\n[Respiración agitada]\n\nVoz: He detectado trazas de un compuesto en mi taza tres noches consecutivas.\nDosis pequeñas, acumulativas. El patrón es consistente con un alcaloide de origen vegetal\no sintético. A esas concentraciones no mata de inmediato. Lo hace parecer un fallo cardíaco.\n\nVoz: Hablé con Noel esta tarde. Me confirmó algo que yo ya sospechaba:\nel sistema de esclusa cambia a modo manual solo cuando alguien activa el protocolo\nde contingencia desde dentro. El nombre del protocolo es MAREA NUEVE.\nNoel me dijo que ese protocolo no debería conocerlo nadie ajeno a sistemas y seguridad.\n\n[Silencio de 6 segundos]\n\nVoz: Alguien ha alterado los registros de turno justo antes de las cero y cuarto.\nEl minuto 03:17 no debería existir en los logs si el reloj maestro funciona correctamente.\nCruzad los horarios con el reporte de esclusa.\n\nVoz: He pedido a Sira Tellez que revise los contratos de aprovisionamiento del último ciclo.\nHay bultos que salieron sin mi firma. Yo no autoricé ninguna exportación de muestras B-9.\n\nVoz (bajando la voz): No confíes en la jefa de seguridad. Ella lo sabe todo. Y ella lo inició.\n\n[Audio termina abruptamente 01:03]" },
          "audio_raal_interceptado.enc": { type: "file", hidden: true, locked: true, password: "MAREA9", content: "[Intercepción de comunicación interna — Cmd. Raal / desconocido — 16/11/2041]\n[Fuente: terminal de respaldo, módulo A]\n\nVoz 1 (Raal): Necesito acceso a los logs de esclusa del último mes.\nVoz 2 (desconocido): Comandante, ese acceso requiere autorización de seguridad.\nVoz 1 (Raal): Soy el comandante de la estación. Tengo autorización máxima.\nVoz 2: La señora Voss ha reclasificado esos registros como documentación de nivel B-3.\n       Solo ella puede aprobar el acceso.\n\n[Pausa larga]\n\nVoz 1 (Raal, en voz baja): Escuchadme bien. Hay algo muy equivocado en esta estación.\nLos tres técnicos del módulo B han presentado síntomas neurológicos en las últimas 48 horas.\nBorda me dijo que no era estrés. Me dijo 'Ivo, alguien nos está envenenando'.\nY ahora no puedo acceder a los registros de seguridad.\n\n[Ruido de conexión cortada]\n\nVoz 1: Aquí el comandante. Esta comunicación queda como registro de mi objeción formal.\nSi algo pasa en las próximas 12 horas, la responsabilidad es de quien controla esos registros.\n\n[Fin de grabación]" }
        }
      },
      logs: {
        type: "dir",
        children: {
          "comedor_memo_77.txt": { type: "file", content: "MEMO INTERNO — SERVICIO DE COMEDOR NOCHE\nTurno: 22:00–02:00  /  Responsable: T. Mena\nFecha: 17/11/2041\n\nINCIDENCIAS DE TURNO:\n  — El Dr. Borda pidió café sin azúcar a las 22:10. Como siempre.\n  — La señora Voss (Seguridad) solicitó a las 22:08 cerrar la máquina expendedora norte\n    por 'mantenimiento preventivo'. No presentó ninguno de los formularios habituales.\n    La máquina estuvo cerrada unos 6 minutos. Luego Voss dijo que 'ya estaba bien'.\n  — A las 01:10 se encontró una taza rota en la bandeja técnica lateral.\n    La taza tenía residuo de café y algo más. Olía extraño. No lo registré en el momento.\n\nANOTACIÓN AL MARGEN (tinta roja, letra diferente — posiblemente Kern):\n  '¿Quién escribe protocolos con nombres de mareas?\n   Vi en la pizarra del turno de seguridad: MAREA NUEVE, subrayado dos veces.\n   Si falta personal en el cambio de turno, revisad la esclusa antes que los dormitorios.'" },
          "turno_seguridad.log": { type: "file", content: "LOG OFICIAL DE TURNO — JEFA DE SEGURIDAD M. VOSS\nFecha: 17/11/2041  /  Turno: 22:00–06:00\n\n22:00  Inicio de turno. Revisión perimetral módulos A, B, C.\n22:08  Accede a comedor. Supervisa servicio nocturno.\n22:14  Regresa a puesto de control principal.\n23:30  Revisión de sistemas. Todo en parámetros.\n00:05  Abandona puesto de control — MOTIVO: no registrado.\n00:30  Regresa a puesto de control.\n00:32  Notifica 'sin novedad' al comandante Raal vía radio interna.\n01:00  Revisión de pasillo B. Reporta normalidad.\n\nNOTA AUTOMÁTICA DEL SISTEMA (marcador rojo):\n  Ausencia no justificada: 00:05 — 00:30 (25 minutos).\n  Cámara de pasillo B OFFLINE durante ese intervalo exacto.\n  El apagado de cámara no consta en ningún registro de mantenimiento del turno.\n  Protocolo exige notificar al comandante cualquier ausencia superior a 10 minutos." },
          "accesos_biometricos.log": { type: "file", hidden: true, content: "LOG DE ACCESOS BIOMÉTRICOS — NEREIDA-9\nPeríodo: 13/11 al 17/11/2041\n\nDR. ELÍAS BORDA:\n  15/11  02:30  Lab. Biología (entrada)\n  15/11  04:15  Lab. Biología (salida)\n  16/11  20:10  Comedor (entrada), 20:55 (salida)\n  17/11  22:05  Comedor (entrada), 22:40 (salida) — Última lectura\n  17/11  23:58  Pasillo Biología — Última LECTURA REGISTRADA\n\nING. NOEL ARAM:\n  13/11  17:45  Terminal OPS (entrada)\n  16/11  21:30  Pasillo B (entrada)\n  17/11  03:09  Pasillo Esclusa B (entrada) — Última LECTURA REGISTRADA\n\nSIRA TELLEZ:\n  15/11  14:00  Legal (entrada)\n  17/11  02:57  Pasillo Esclusa B (entrada) — Última LECTURA REGISTRADA\n\nMARA VOSS:\n  17/11  22:00  Puesto control (entrada)\n  17/11  00:05  Puesto control (salida) — SIN REENTRADA HASTA 00:30\n  [NOTA: lectura biométrica suspendida en pasillo B durante ausencia]\n\nLIA KERN:\n  17/11  22:00  Cabina Radio (entrada)\n  17/11  07:02  Cabina Radio (salida)\n  [Sin interrupciones — coartada completa]" },
          "camaras_offline.log": { type: "file", hidden: true, content: "LOG DE INCIDENCIAS — SISTEMA DE CÁMARAS\nNereida-9 / Período: 10/11 — 17/11/2041\n\nEVENTOS DE DESCONEXIÓN:\n\n  10/11  02:55–03:10  Cámara Pasillo B       — usuario: n9_sec\n  12/11  02:50–03:08  Cámara Pasillo B       — usuario: n9_sec\n  14/11  02:55–03:06  Cámara Pasillo B       — usuario: n9_sec\n  16/11  02:59–03:07  Cámara Pasillo B       — usuario: n9_sec\n  17/11  00:05–00:30  Cámara Pasillo B       — usuario: n9_sec\n\nNOTA DEL SISTEMA:\n  El usuario 'n9_sec' corresponde a la cuenta de servicio de seguridad.\n  Normalmente opera en modo automático. Los apagados manuales requieren\n  confirmación del jefe de turno. Ninguna de estas sesiones tiene confirmación.\n\nNOTA MANUSCRITA (papel pegado al log impreso, letra de Noel Aram):\n  'La cuenta n9_sec no tiene credenciales propias.\n   Se activa con las claves del jefe de seguridad activo.\n   Quién apagó esas cámaras: Voss. Sin ninguna duda.'" }
        }
      },
      ops: {
        type: "dir",
        children: {
          "reporte_esclusa.log": { type: "file", hidden: true, content: "REPORTE DE EVENTOS — ESCLUSA B\nFecha: 17/11/2041  /  Modo activo: mantenimiento remoto\n\n02:58  Solicitud de prueba de sellado (usuario: n9_sec)\n03:04  Cambio a modo manual — origen: terminal de movilidad (Pasillo B)\n03:09  Puerta interna cerrada — lecturas biométricas de Aram, Tellez y Borda EN INTERIOR\n03:11  Solicitud de liberación de puerta externa (usuario: n9_sec)\n03:17  EVENTO SIN FIRMA DIGITAL — REGISTRO HUÉRFANO\n        [El reloj maestro no registra este minuto en el historial sincronizado]\n03:18  Alarma local de la esclusa silenciada desde el interior\n03:22  Puerta externa abierta 4 segundos — presión igualada\n03:24  Estado restablecido (usuario: n9_sec) — puerta interna sin respuesta\n03:26  Sistema de emergencia de esclusa: OFFLINE\n\nNOTA AUTOMÁTICA: manipulación de timestamp detectada — probabilidad 94%\n\nNOTA MANUSCRITA (N. Aram, interior de la cubierta del log):\n  'No es un fallo técnico. Es una mano humana.\n   Me metieron aquí a punta de amenaza. Yo abrí la puerta interna.\n   No tuve elección. Lo siento, Elías. Lo siento, Sira.'" },
          "bitacora_noel.txt": { type: "file", hidden: true, content: "BITÁCORA TÉCNICA — ING. NOEL ARAM\nFecha: 13 al 16 de noviembre de 2041\n\n--- 13/11 ---\nHe encontrado un relay de red conectado a mi terminal de sistemas.\nNo es equipo de la estación. Alguien lo instaló mientras yo no estaba.\nEste tipo de dispositivo permite suplantar credenciales en el bus de datos.\nEs decir: alguien puede usar mis permisos sin que yo lo sepa.\n\n--- 14/11 ---\nConfirmado: el relay fue usado para acceder al puerto RK-44.\nEse puerto es una vía de datos de respaldo que no aparece en los logs principales.\nSolo yo y el Dr. Borda sabíamos que existía. Y ahora también sabe quién instaló el relay.\n\nEl código del puerto: RK-44.\nEl código de salida de los datos exportados: VANTA.\n\n--- 16/11 ---\nHe rastreado cuatro accesos nocturnos al puerto RK-44 en los últimos siete días.\nSiempre entre las 03:00 y las 03:05. Usuario suplantado: n9_sec (cuenta de servicio de seguridad).\n\nBuscad los pagos bajo el alias VANTA.\nTodo el tráfico financiero de esta operación usa ese código.\nLa cuenta de destino está fuera de la estación. Offshore. No puedo rastrearla desde aquí.\n\nLe conté todo a Borda hoy. Me dijo que Sira Tellez puede cruzar esos datos con los contratos.\nMañana lo ponemos todo junto y vamos a Raal.\n\nFirmado: N. Aram\n\nP.D.: Si encuentran esto sin encontrarme a mí, sabed lo que significa." },
          "red_nucleo.enc": { type: "file", hidden: true, locked: true, password: "RK44", content: "DUMP PARCIAL DE RED — PUERTO OCULTO NEREIDA-9\nRecuperado de caché del bus de datos\n\nPUERTO: RK-44 (acceso de respaldo, no documentado en manual oficial)\nCÓDIGO DE SESIÓN DE SALIDA: VANTA\n\nHISTORIAL DE ACCESOS AL PUERTO RK-44:\n  10/11  03:02 — usuario: m_voss  (1.4 GB exportados)\n  12/11  02:58 — usuario: m_voss  (0.9 GB exportados)\n  14/11  03:00 — usuario: m_voss  (2.1 GB exportados)\n  16/11  03:00 — usuario: m_voss  (1.7 GB exportados)\n\nPATRÓN: accesos nocturnos regulares, mismo usuario, mismo intervalo de tiempo.\nTipo de datos: muestras cifradas (extensión .bio.enc) — origen: Lab. Biología\n\nDESTINO EXTERNO (parcialmente recuperado):\n  Servidor de recepción: VANTA-RELAY-07 [IP no resolvible desde esta red]\n  Identificación del cliente: SOLVANG ASSET TRUST\n\nFRAGMENTO DE CACHÉ CIFRADO (descifrado parcialmente):\n  'Ella exigió cortar cabos antes del amanecer del ciclo 7.\n   Los tres técnicos habían encontrado piezas del mismo puzzle por separado.\n   Voss los eliminó antes de que pudieran unirlas.'" },
          "manifiesto_carga.txt": { type: "file", hidden: true, content: "MANIFIESTO DE CARGA — CICLO NOVIEMBRE 2041\nNereida-9 / Responsable: Mara Voss (Seguridad / Logística)\n\nSALIDAS AUTORIZADAS:\n  3 x caja estándar material de laboratorio (consumibles)\n  2 x caja residuos no peligrosos (protocolo estándar)\n\nSALIDAS SIN FIRMA DEL BIÓLOGO RESPONSABLE:\n  3 x bulto marcado 'MUESTRA BIOLÓGICA CÓD. NTX'\n    — Firmado por: M. Voss\n    — Sin contrafirma del Dr. Borda (OBLIGATORIA por protocolo para material biológico)\n    — Destino declarado: 'laboratorio externo, clasificado'\n\nNOTA DE AUDITORÍA (Sira Tellez, 15/11/2041):\n  'Estos tres bultos no tienen número de expediente científico.\n   La firma de Voss no tiene autoridad para exportar material biológico.\n   El Dr. Borda no fue consultado. Se lo comuniqué hoy. Se puso pálido.'\n\nNOTA AL MARGEN (letra de Borda, tinta roja):\n  'Yo nunca firmé esto. Nunca. Mara: si lees esto, ya es demasiado tarde para ti.'" }
        }
      },
      bio: {
        type: "dir",
        children: {
          "nota_kern_observaciones.txt": { type: "file", hidden: true, content: "NOTAS DE CAMPO — LIA KERN\nSemana del 13 al 17 de noviembre de 2041\n\nLunes 13:\n  Vi a Voss en el laboratorio de biología a las 02:30 de la madrugada.\n  No es su área de acceso habitual. Manipulaba las muestras del módulo B-9.\n  Le pregunte qué hacía. Me dijo que 'revisión rutinaria de seguridad'.\n  Nunca había oído eso antes.\n\nMiércoles 15:\n  El volumen de la muestra B-9 había bajado un 40% sin justificación en el libro de registro.\n  Borda estaba muy agitado. Dijo que era imposible que se perdiera tanto por evaporación.\n  La firma de último acceso era m_voss.\n\nJueves 16:\n  Elías fue a hablar con Voss directamente a las 20:00. Fue al despacho de seguridad.\n  Me llamó a las 23:00. Estaba nervioso. Dijo textualmente:\n  'Lia, si no te llamo mañana a las 09:00, busca mi pez.'\n  No entendía a qué se refería hasta que recordé el audio de emergencia.\n\nViernes 17:\n  Borda no apareció en el turno de mañana. A las 09:15 lo encontraron.\n  Voss fue la primera en entrar a su módulo. La agenda de apuntes de Elías había desaparecido.\n  No la vi cuando entré yo, diez minutos después." },
          "informe_muestras_b9.txt": { type: "file", hidden: true, content: "INFORME DE CONTROL DE MUESTRAS — LABORATORIO BIOLOGÍA\nResponsable: Dr. Elías Borda\nFecha de redacción: 15/11/2041\n\nMUESTRA AFECTADA: B-9 (agente neuotrófico de origen abisal, sin clasificación oficial)\nUbicación: módulo de biología, cámara fría 4-B\n\nVOLUMEN AL INICIO DEL CICLO (01/11):   450 ml\nVOLUMEN ACTUAL (15/11):                265 ml\nDIFERENCIA NO JUSTIFICADA:             185 ml\n\nFIRMA DE Último ACCESO EN LOG DIGITAL: m_voss (sin autorización del biólogo responsable)\nFECHA Y HORA:                          15/11/2041, 02:30\n\nEVALUACIÓN:\nLa muestra B-9 no experimenta evaporación apreciable en cámara fría a -4°C.\nLa única vía de reducción es extracción mecánica. 185 ml equivalen a 9-10 dosis\nde concentrado puro, suficientes para contaminar agua, alimentos o bebidas de\ntoda la tripulación durante semanas a dosis no letales.\n\nNOTA AL MARGEN (Borda, rotulador rojo):\n  'Si hay transacción económica vinculada, buscad el alias VANTA.\n   Ese nombre aparece en el registro de red de Noel.'" },
          "registro_experimento.txt": { type: "file", hidden: true, content: "LIBRO DE REGISTRO — INVESTIGACIÓN B-9\nDr. Elías Borda  /  Ciclos mayo 2040 — noviembre 2041\n\n--- NATURALEZA DEL AGENTE B-9 ---\nDescubierto en las muestras del zanjón Nereida (2.700 m) en octubre de 2039.\nPropiedad química: modula la actividad del sistema nervioso autónomo.\nEfecto en dosis bajas (crónica): deterioro cognitivo, letargia, muerte cardíaca aparente.\nEfecto en dosis medias: paresia muscular, confusión severa, inconsciencia.\nEfecto en dosis altas: fallo multiorgánico en 2-6 horas.\n\n--- APLICACIONES POTENCIALES ---\nMédicas (supresión de dolor neuropático severo): MUY PROMETEDOR.\nNo médicas: clasificadas como peligrosas en el protocolo ético firmado por todos los tripulantes.\n\n--- Última ENTRADA (14/11/2041) ---\nAlguien ha tomado 185 ml de la cámara 4-B sin registrarlo.\nSi ese volumen se administra en dosis diarias en bebidas calientes (café, infusiones),\nel receptor no detectaría nada en los primeros días.\nEl patrón sería: debilidad progresiva, deterioro cardíaco aparente, muerte.\nSin análisis toxicológico específico, pasaría por un fallo cardíaco natural.\n\nEsto no es especulación. Esto es lo que me está pasando a mí." },
          "ficha_agente_b9.enc": { type: "file", hidden: true, locked: true, password: "MUESTRA", content: "FICHA TÉCNICA CLASIFICADA — AGENTE BIOLÓGICO B-9\nDocumento de acceso restringido — Dr. Borda / Corporación Solvang\n\nNOMBRE QUÍMICO: Nereidina-9 (denominación de trabajo)\nCLASIFICACiÓN CORPORATIVA: Activo de alto valor (AV-1)\n\nVALOR DE MERCADO ESTIMADO (concentrado puro, 100 ml):\n  Aplicación médica legal:          aprox. 180.000 USD\n  Mercado no regulado (defensa/inteligencia): aprox. 2.400.000 USD\n\nESTATUS DE PROPIEDAD INTELECTUAL:\n  Derechos de descubrimiento: Dr. Elías Borda (personal)\n  Acuerdo de cesión firmado: PENDIENTE (Borda se negó en octubre 2041)\n  Comunicación corporativa interna (Solvang):\n    'Si Borda no firma la cesión voluntariamente antes del fin del ciclo 7,\n     activar el protocolo de recuperación de activos.'\n\nNOTA DEL AUDITOR:\n  'Protocolo de recuperación de activos' es el eufemismo usado internamente\n  para eliminar físicamente al investigador que posee los derechos.\n  Este documento establece el motivo real del asesinato del Dr. Borda." }
        }
      },
      medico: {
        type: "dir",
        children: {
          "historial_borda.txt": { type: "file", hidden: true, content: "HISTORIAL MÉDICO — DR. ELÍAS BORDA\nEnfermería Nereida-9 / Ciclo noviembre 2041\n\nCONSULTAS REGISTRADAS (noviembre):\n  06/11  Revisión rutinaria. Estado: óptimo.\n  12/11  Consulta voluntaria. Síntomas: fatiga leve, sensación de presión cardíaca.\n         Evaluación: estrés por jornadas largas. Sin medicación.\n  14/11  Nueva consulta. Síntomas: fatiga acentuada, ligera pérdida de coordinación fina.\n         Borda: 'No es estrés. He visto estos síntomas en experimentos de laboratorio.'\n         No se registró medicación ni derivación.\n  16/11  Consulta urgente nocturna. Borda llegó a las 23:00 con taquicardia.\n         Solicitó análisis de sangre completo con panel toxicológico.\n         SOLICITUD DENEGADA por la jefa de seguridad Voss, que estaba presente en enfermería.\n         Motivo aducido por Voss: 'Procedimiento de análisis fuera de horario de enfermería.'\n         BORDA: 'Esto es una emergencia médica. Exijo el análisis.'\n         VOSS: 'El comandante Raal ya ha sido informado. Descanse, doctor.'\n\nNOTA DEL SANITARIO (F. Adis, enfermero de guardia):\n  'Nunca había visto a Voss en enfermería. El doctor tenía razón en exigir el análisis.\n   Le hice un electrocardiograma rápido. Mostraba irregularidades leves pero reales.\n   Cuando salí a buscar los reactivos del panel toxicológico, Borda había desaparecido.\n   Voss dijo que había vuelto a su módulo.'" },
          "toxicologia.txt": { type: "file", hidden: true, content: "INFORME TOXICOLÓGICO POST-MORTEM — DR. ELÍAS BORDA\nPreparado por: F. Adis, Enfermero Senior  /  Fecha: 19/11/2041 (dos días después del incidente)\n\n[Este informe fue elaborado a partir de muestras de cabello del Dr. Borda\n guardadas en el archivo médico como parte del protocolo rutinario de higiene.]\n\nANÁLISIS DE CABELLO (cronología de últimas 3 semanas):\n  Semana 1 (01-07/11): Sin trazas de sustancias anormales.\n  Semana 2 (08-14/11): Presencia de compuesto orgánico no identificado (trazas).\n                       Compatible con alcaloide de origen marino.\n  Semana 3 (15-17/11): Concentración del mismo compuesto x4 respecto a semana 2.\n                       Patrón consistente con administración diaria acumulativa.\n\nCONCLUSIÓN:\n  El Dr. Borda fue envenenado de forma sistemática durante al menos 9-10 días.\n  El compuesto es consistente con el agente B-9 del laboratorio de biología.\n  La causa de muerte física no fue solo el envenenamiento:\n  el sujeto fue encerrado en la esclusa B en estado de debilidad severa.\n\n[Informe no enviado al informe oficial. Guardado en archivo médico local.]" },
          "autopsia_borda.enc": { type: "file", hidden: true, locked: true, password: "FORENSE", content: "INFORME DE AUTOPSIA — DR. ELÍAS BORDA\nPreparado por: Comisión de Investigación Marítima Profunda (2058, 17 años después)\nA partir de restos conservados en la esclusa sellada.\n\nCAUSA DE MUERTE REAL:\n  Combinación de intoxicación crónica por agente neurotrófico marino\n  y muerte por descompresión brusca (exposición al exterior de la esclusa B).\n\nHALLAZGOS ÓSEOS Y TISULARES:\n  Marcadores de intoxicación en tejido óseo: positivo (alcaloide marino)\n  Lesiones por onda de presión: consistentes con apertura de esclusa en condiciones abisales\n\nCONCLUSIÓN OFICIAL DE LA COMISIÓN:\n  El Dr. Borda fue envenenado de forma premeditada durante varios días\n  y posteriormente ejecutado mediante un mecanismo de esclusa manipulado.\n  Esto es un homicidio con premeditación. No un accidente de presión.\n\nRESPONSABLE SEÑALADO:\n  Mara Voss (jefa de seguridad, Nereida-9, ciclo nov. 2041)\n  Detenida en 2058 gracias a este expediente de recuperación." }
        }
      },
      personal: {
        type: "dir",
        children: {
          "ficha_borda.txt": { type: "file", content: "FICHA DE PERSONAL — DR. ELÍAS BORDA\nCargo: Biólogo Jefe / Investigador Principal\nNacimiento: 1990. Nacionalidad: española.\nFormación: Doctorado en Farmacología Marina, Universidad de Barcelona.\nPublicaciones: 34 artículos. Dos premios internacionales de investigación abisal.\nAntigüedad en Nereida-9: desde la inauguración (2034). 7 años.\n\nNOTA DE RRHH:\n  'El Dr. Borda rechazó en octubre de 2041 firmar el acuerdo de cesión de derechos\n   sobre el agente B-9 a Solvang Corp. Lo hizo por escrito y con asistencia jurídica.'\n\nNOTA DE CORPORACIÓN (Solvang Corp, nivel ejecutivo):\n  'Borda es el único obstáculo legal para la comercialización de B-9.\n   Resolver antes del fin del ciclo 7.' [fecha: 05/11/2041]" },
          "ficha_kern.txt": { type: "file", content: "FICHA DE PERSONAL — LIA KERN\nCargo: Técnico de Radio y Comunicaciones\nNacimiento: 2008. Nacionalidad: alemana.\nFormación: Ingeniería de Telecomunicaciones (summa cum laude, Munich).\nAntigüedad en Nereida-9: 4 años.\n\nNOTA DE EVALUACIÓN (Raal, 2041):\n  'Kern es la mejor operadora de radio que hemos tenido. Hiperobservadora.\n   A veces su curiosidad me preocupa, pero en situaciones de crisis es invaluable.'" },
          "ficha_voss.txt": { type: "file", hidden: true, content: "FICHA DE PERSONAL — MARA VOSS\nCargo: Jefa de Seguridad\nNacimiento: 1997. Nacionalidad: suiza / alemana.\nFormación: Seguridad corporativa (Meridian BioSec), operaciones en campo.\nAntigüedad en Nereida-9: 2 años (contratación directa por Solvang Corp, no por Nereida).\n\nHISTORIAL PREVIO:\n  2030-2039: Operaciones de campo para Meridian BioSec (filial de Solvang).\n  2039:      Investigada por desaparición de testigo en caso de exportación ilegal.\n             Caso archivado por falta de pruebas.\n  2039:      Contrato firmado bajo nombre anterior: Mara Eiden.\n\nNOTA DE RRHH (interna, Solvang Corp):\n  'Voss ha completado con éxito cinco operaciones de recuperación de activos biológicos.\n   Su historial la hace ideal para la situación de Nereida-9.'" },
          "ficha_aram.txt": { type: "file", hidden: true, content: "FICHA DE PERSONAL — ING. NOEL ARAM\nCargo: Ingeniero de Sistemas e Infraestructura\nNacimiento: 2003. Nacionalidad: turca / francesa.\nFormación: Ingeniería de Sistemas Autónomos, Paris-Saclay.\nAntigüedad en Nereida-9: 5 años.\n\nNOTA DE EVALUACIÓN (Raal, 2040):\n  'Aram es mi mejor técnico. Paranoidamente documentador: guarda copias de todo.\n   Si algo falla en esta estación, Noel lo encontrará antes que el sistema automático.'\n\nNOTA MANUSCRITA DE KERN (pegada a la ficha):\n  'Si encuentran a Noel después de que todo esto se limpie,\n   recordad que él no abrió esa puerta por voluntad propia.\n   Le obligaron. Eso lo sé porque conozco a Noel.'" },
          "contrato_voss.enc": { type: "file", hidden: true, locked: true, password: "EIDEN", content: "CONTRATO DE SERVICIOS ESPECIALES — RECUPERACIÓN DE ACTIVOS\nSolvang Asset Trust / Meridian BioSec Security Division\n\nCONTRATISTA: Mara Eiden (alias operativo: Voss)\nCLIENTE: Solvang Asset Trust\nOBJETO: Recuperación del activo biológico B-9 (Nereidina-9) de la estación Nereida-9.\n\nOBLIGACIONES DEL CONTRATISTA:\n  1. Establecer un canal de exportación de datos y muestras físicas (alias: VANTA).\n  2. Neutralizar cualquier obstáculo legal o personal a dicha exportación.\n  3. Garantizar que la operación no deje rastro documental en los sistemas de la estación.\n  4. En caso de exposición inminente, activar el protocolo de cierre limpio.\n\nRETRIBUCIÓN:\n  500.000 CHF por la exportación completa del agente B-9.\n  Prima de 150.000 CHF adicionales por resolución completa sin rastro legal.\n\nFIRMA: Mara Eiden — fecha: 03/09/2041\nFIRMA CORPORACIÓN: [redactado]\n\nNOTA: Este contrato establece el motivo económico del asesinato de Borda, Aram y Tellez." }
        }
      },
      comunicaciones: {
        type: "dir",
        children: {
          "radiograma_entrada.txt": { type: "file", content: "RADIOGRAMA ENTRANTE — 16/11/2041 / 18:43 UTC\nOrigen: Centro de Operaciones Solvang Corp\nDestino: Estación Nereida-9 / Cmd. Ivo Raal\n\n'Comandante Raal:\n\nHemos recibido su solicitud de revisión del protocolo del Dr. Borda.\nLe informamos que el ciclo de operaciones 7 se cierra a las 24:00 del 17 de noviembre.\nTodos los activos biológicos del laboratorio deben ser transferidos al equipo\nde relevo según el protocolo estándar de fin de ciclo.\n\nSolvang Corp agradece la dedicación de toda la tripulación.\nEl equipo de relevo llegará el 18 de noviembre a las 10:00.'\n\nNOTA MANUSCRITA DE RAAL (al margen del impreso):\n  'Me mandaron a Voss en lugar de un equipo médico.\n   Y el equipo de relevo llega el día DESPUÉS del fin de ciclo.\n   Alguien quería que todo terminara antes de que llegara nadie.'" },
          "mensajes_borrados.enc": { type: "file", hidden: true, locked: true, password: "VANTA", content: "RECUPERACIÓN DE MENSAJES BORRADOS — TERMINAL SEGURIDAD\nRecuperados del búfer de escritura del disco de Voss\n\n[Mensaje 1 — 15/11 — 23:41]\nDE: m_voss@n9sec\nPARA: vanta-relay-07@[cifrado]\n'Cuarta exportación completada. Total: 6.1 GB de datos B-9.\nBorda ha descubierto la sustracción de muestras. Hay que acelerar.\nActivando protocolo de cierre al final del ciclo 7. Confirmar recepción.'\n\n[Respuesta — 15/11 — 23:59]\n'Confirmado. Procede con el protocolo de cierre limpio.\nNecesitamos los tres neutralizados: Borda, Aram y Tellez.\nLa chica de radio no importa: no sabe nada concreto.\nRaal estará en contención y no podrá interferir.'\n\n[Mensaje 2 — 17/11 — 03:28]\nDE: m_voss@n9sec\nPARA: vanta-relay-07@[cifrado]\n'Protocolo completado. Los tres han salido por la esclusa B.\nRaal en contención. Kern en la cabina sin acceso exterior.\nMe voy en el siguiente transporte. Borrado de logs iniciado.'\n\n[FIN DE RECUPERACIÓN — algunos bloques siguen cifrados]" },
          "intercepcion_corporativa.txt": { type: "file", hidden: true, content: "INTERCEPCIÓN DE COMUNICACIÓN CORPORATIVA\nCapturada por: Comisión de Investigación Marítima, 2058\nOrigen: Archivos internos Solvang Corp / Meridian BioSec\n\nCORREO INTERNO — NIVEL EJECUTIVO — 01/11/2041:\nDE: Consejo Ejecutivo, Solvang Corp\nPARA: Meridian BioSec, Responsable de Operaciones\n\n'El activo Nereidina-9 (B-9) tiene un valor estimado de mercado no regulado\nde entre 800 millones y 1.200 millones de dólares en el sector de defensa biológica.\n\nEl Dr. Borda es el único propietario legal del descubrimiento.\nSu negativa a ceder los derechos en octubre es un obstáculo inaceptable.\n\nSe autoriza la operación EIDEN con plena cobertura corporativa.\nMara Eiden ha sido activada en la estación bajo cobertura de jefa de seguridad.\nSe espera resolución completa antes del cierre del ciclo 7 (17/11).\n\nEste correo es autoborrable en 72 horas. Copia en sobre cerrado en sede central.'\n\n[NOTA DEL FISCAL: Este correo fue recuperado de un servidor de respaldo que Solvang\nno sabía que existía. Fue la clave para procesar a los directivos de la corporación.]" }
        }
      },
      legal: {
        type: "dir",
        children: {
          "legal_sira_audio.transcript": { type: "file", hidden: true, content: "[Grabación de audio — Sira Tellez — 17/11/2041 — 02:30]\n[Encontrada en el módulo de comunicaciones legales, sin fecha de borrado]\n\nVoz (Sira Tellez): Si este registro aparece, significa que ya me encontraron.\n\n[Pausa de 4 segundos]\n\nVoz: He cruzado los contratos de aprovisionamiento con los accesos biométricos de seguridad.\nEl alias VANTA aparece en cuatro transferencias de datos salientes en los últimos 7 días.\nCada transferencia coincide en hora y día con los accesos de m_voss al puerto RK-44.\n\nVoz: El apellido de soltera de Mara Voss aparece en los contratos más antiguos que encontré.\nLo firmó con su nombre anterior: Eiden. Mara Eiden.\nEsa firma conecta todos los documentos con la misma persona.\n\nVoz: Tenía los contratos impresos en mi módulo. Esta tarde desaparecieron.\nVoss entró mientras yo estaba en el comedor. La vi salir cuando regresaba.\n\n[Ruido estático de 6 segundos]\n\nVoz: Noel me pidió que fuera a la esclusa B esta noche a las 03:00.\n     Dice que tiene algo que mostrarme en el sistema de la esclusa.\n     No me gusta ese plan, pero Noel no me pediría algo así sin una razón.\n     Si no regreso, buscad el nombre EIDEN en todos los archivos.\n     Ese nombre es la llave.\n\n[Audio termina abruptamente 02:49]" }
        }
      },
      private: {
        type: "dir",
        children: {
          "veredicto_final.evd": { type: "file", locked: true, password: "EIDEN", content: "VEREDICTO FINAL — CASO NEREIDA-9\nComisión de Investigación Marítima Profunda\nFecha de cierre: 14 de marzo de 2058 (17 años después de los hechos)\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nRESPONSABLE PRINCIPAL: Mara Voss (nombre real: Mara Eiden)\nJefa de Seguridad, Estación Nereida-9, ciclo noviembre 2041\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nVÍCTIMAS:\n  Dr. Elías Borda    — Biólogo jefe. Envenenado sistemáticamente. Ejecutado en esclusa B.\n  Ing. Noel Aram     — Ingeniero de sistemas. Coercionado para abrir la esclusa. Ejecutado.\n  Sira Tellez        — Analista jurídica. Ejecutada en esclusa B.\n\nMOTIVO:\n  Voss fue contratada por Solvang Corp / Meridian BioSec bajo el alias de operación EIDEN\n  para extraer el agente biológico B-9 (Nereidina-9) de la estación Nereida-9\n  y eliminar cualquier obstáculo legal a su comercialización.\n  El Dr. Borda había rechazado ceder los derechos del descubrimiento.\n  Aram y Tellez habían descubierto la operación por separado.\n\nMÉTODO:\n  Borda: envenenamiento acumulativo mediante agente B-9 en bebidas. Varios días.\n  Los tres: encierro en la esclusa B usando el protocolo MAREA NUEVE de forma ilícita.\n            Apertura de la compuerta exterior. Presión abisal instantánea.\n  Raal: confinado en módulo de contención mediante protocolo activado desde el puesto de Voss.\n  Kern: aislada en cabina de radio. No fue eliminada porque 'no sabía nada concreto'.\n\nPRUEBAS DETERMINANTES:\n  1. Contrato EIDEN (firmado bajo nombre real de Voss con Solvang/Meridian)\n  2. Grabación de audio de Sira Tellez (menciona alias EIDEN como clave)\n  3. Dump de red RK-44 (patrón de accesos m_voss con código VANTA)\n  4. Mensajes borrados recuperados del terminal de Voss\n  5. Informe toxicológico de F. Adis (envenenamiento crónico confirmado)\n  6. Bitácora de Noel Aram (relay + código RK-44 + alias VANTA)\n  7. Intercepción corporativa (autorización de Solvang para la operación)\n\nSENTENCIA:\n  Mara Voss: cadena perpetua. Detenida en Buenos Aires en 2057.\n  Directivos de Solvang Corp: procesados por complicidad. Penas de 15 a 25 años.\n  La empresa Solvang fue disuelta por orden judicial en 2059.\n\nEXPEDIENTE CERRADO." }
        }
      }
    }
  },
  databases: {
    protocolos: {
      marea9: { text: "PROTOCOLO MAREA NUEVE localizado en logs de esclusa. Nuevos archivos revelados.", reveal: ["/ops/reporte_esclusa.log", "/ops/bitacora_noel.txt"] },
      exportacion: { text: "Manifiesto de carga del ciclo recuperado. Exportaciones sin firma identificadas.", reveal: ["/ops/manifiesto_carga.txt"] }
    },
    turnos: {
      "0317": { text: "Anomalía en registro de turno a las 03:17 confirmada. Bitácora de Aram y reporte de esclusa accesibles.", reveal: ["/ops/reporte_esclusa.log", "/ops/bitacora_noel.txt"] }
    },
    finanzas: {
      vanta: { text: "Alias VANTA identificado en red interna. Audio de Tellez y volcado de red accesibles.", reveal: ["/legal/legal_sira_audio.transcript", "/ops/red_nucleo.enc"] },
      eiden: { text: "Nombre EIDEN rastreado en archivos de personal. Contrato cifrado de Voss accesible.", reveal: ["/personal/contrato_voss.enc"] }
    },
    biologia: {
      borda: { text: "Notas de campo de Kern y reporte de muestras B-9 recuperados.", reveal: ["/bio/nota_kern_observaciones.txt", "/bio/informe_muestras_b9.txt"] },
      muestras: { text: "Informe completo de sustracción de muestras disponible. Registro del experimento accesible.", reveal: ["/bio/informe_muestras_b9.txt", "/bio/registro_experimento.txt"] },
      experimento: { text: "Registro de investigación B-9 con notas personales de Borda encontrado.", reveal: ["/bio/registro_experimento.txt"] },
      agente: { text: "Ficha técnica clasificada del agente B-9 accesible (cifrada).", reveal: ["/bio/ficha_agente_b9.enc"] }
    },
    medico: {
      borda: { text: "Historial médico del Dr. Borda de noviembre 2041 recuperado.", reveal: ["/medico/historial_borda.txt"] },
      autopsia: { text: "Informe de autopsia de la Comisión de 2058 accesible (cifrado).", reveal: ["/medico/autopsia_borda.enc"] },
      alcaloide: { text: "Informe toxicológico de F. Adis recuperado. Envenenamiento confirmado.", reveal: ["/medico/toxicologia.txt"] }
    },
    seguridad: {
      biometria: { text: "Log de accesos biométricos de la semana del incidente recuperado.", reveal: ["/logs/accesos_biometricos.log"] },
      camaras: { text: "Log de incidencias de cámaras con patrón de apagados recuperado.", reveal: ["/logs/camaras_offline.log"] }
    },
    personal: {
      voss: { text: "Ficha de personal de Mara Voss con historial corporativo previo accesible.", reveal: ["/personal/ficha_voss.txt"] },
      aram: { text: "Ficha de personal de Noel Aram recuperada.", reveal: ["/personal/ficha_aram.txt"] }
    },
    comunicaciones: {
      eliminados: { text: "Mensajes borrados del terminal de Voss parcialmente recuperados (cifrados).", reveal: ["/comunicaciones/mensajes_borrados.enc"] },
      corporacion: { text: "Intercepción de comunicación interna de Solvang Corp recuperada.", reveal: ["/comunicaciones/intercepcion_corporativa.txt"] },
      raal: { text: "Grabación interceptada de comunicación del Comandante Raal accesible (cifrada).", reveal: ["/audio/audio_raal_interceptado.enc"] }
    },
    audio: {
      kern3: { text: "Tercer audio de Kern (18/11) con detalles del comportamiento de Voss recuperado.", reveal: ["/audio/audio_kern_03.transcript"] }
    }
  }
};
