// CASO 4 — SEÑAL PERDIDA
var CASE4 = {
  title: "Senal Perdida",
  year: "2089",
  setting: "Estacion orbital Helios-3, orbita baja terrestre",
  tagline: "Siete tripulantes muertos. Un experimento sin consentimiento. El cientifico escapo solo.",
  intro: "14 de enero de 2089. La estacion Helios-3 fue declarada perdida. Cero supervivientes.\nCausa oficial: fallo en cadena de soporte vital.\nSeis meses despues, la sonda de recuperacion Artemis encontro la caja negra.\nEsta sesion de recuperacion contiene lo que queda. Descubre que hizo el Dr. Cassius.",
  solveFile: "registro_final.evd",
  startFiles: [
    "/bienvenida.txt",
    "/bitacoras/bitacora_general.txt",
    "/bitacoras/diario_tecnico.txt",
    "/experimentos/protocolo_helio.txt",
    "/comunicaciones/transmision_01.txt",
    "/tripulacion/ficha_oretz.txt",
    "/tripulacion/ficha_cassius.txt",
    "/conclusion/registro_final.evd"
  ],
  hints: [
    "Lee la bitacora de Oretz. Menciona a su hija de 9 anos. El nombre de la hija es la primera clave.",
    "cd bitacoras → unlock ultimo_mensaje_oretz.enc LYRA — El mensaje revela el codigo admin de la estacion.",
    "cd experimentos → unlock resultados_ocultos.enc CERO — Los resultados muestran el plan de Cassius.",
    "Usa 'search doctor experimento' para el perfil real de Cassius del Consorcio.",
    "Usa 'search oxigeno fallo' para ver el log del crimen paso a paso.",
    "cd sistemas → unlock acceso_admin.enc HELIO para ver todos los accesos de Cassius.",
    "Usa 'search prometeo plan' para acceder al manifiesto de Cassius.",
    "El punto de destino de la capsula de Cassius es la ultima clave. Usa 'examine capsula'.",
    "Comandos extra: map, timeline, evidence, profile [nombre], examine [termino]."
  ],
  map: "HELIOS-3 — ESTACION ORBITAL\n" +
    "Orbita: 387 km. Inclinacion: 28.5°\n" +
    "═══════════════════════════════════════════════════\n" +
    "  ┌────────────────┐  ┌────────────────┐\n" +
    "  │  MODULO MANDO  │  │  LABORATORIO   │\n" +
    "  │  (Oretz)       │  │  (Cassius)     │\n" +
    "  └───────┬────────┘  └────────┬───────┘\n" +
    "          └──────────┬──────────┘\n" +
    "  ┌──────────────────┴─────────────────────┐\n" +
    "  │           NUCLEO CENTRAL               │\n" +
    "  │     (acceso a todos los modulos)       │\n" +
    "  └────┬──────────────────────┬────────────┘\n" +
    "       │                      │\n" +
    "  ┌────┴───────┐       ┌──────┴────────────┐\n" +
    "  │  MODULO 3  │       │  SISTEMAS SOPORTE │\n" +
    "  │  TRIPULACION│      │  VITAL / OPS      │\n" +
    "  │  (7 pers.) │       │                   │\n" +
    "  └────────────┘       └───────────────────┘\n" +
    "  ┌────────────┐       ┌───────────────────┐\n" +
    "  │  CAPSULA   │       │  COMUNICACIONES   │\n" +
    "  │ EMERGENCIA │       │  (transm. Tierra) │\n" +
    "  └────────────┘       └───────────────────┘\n" +
    "  ★ ORION-447: Estacion privada del Consorcio (destino de Cassius)",
  profiles: {
    oretz: "COMANDANTE YAEL ORETZ — Victima (lider de la tripulacion)\nEdad: 41. Israelita. Piloto de orbita. Comandante desde 2085.\nHija: Lyra Oretz, 9 anos (en Tierra, en custodia del padre).\nDescubrio que el experimento CERO no era lo que les habian dicho.\nIntento cerrar el experimento manualmente la noche del 13 de enero.\nMurio en Helios-3 la madrugada del 14 de enero de 2089.",
    cassius: "DR. FENN CASSIUS — Principal responsable\nEdad: 48. Britanico. Neurocientifico y farmacologista.\nEspecialidad declarada: adaptacion del sistema nervioso en microgravedad.\nEspecialidad real: desarrollo de agentes neurotroficos para control militar.\nContratado por el Consorcio Artemis con pleno conocimiento de la metodologia real.\nEvacu\u00f3 la estacion en capsula personal a las 01:00. Fue detenido en ORION-447 en julio de 2089.",
    novak: "ING. PETRA NOVAK — Victima (ingenieria de sistemas)\nEdad: 35. Checa. Especialidad: sistemas de soporte vital y monitorizacion atmosferica.\nDescubrio que alguien habia falsificado las lecturas de O2 del modulo 3.\nInformo a Oretz el 12 de enero. No pudo impedirlo.\nMurio en Helios-3 la madrugada del 14 de enero de 2089.",
    dao: "OFICIAL SEREN DAO — Investigadora\nEdad: 29. Mision de recuperacion Artemis, sonda enviada 6 meses despues.\nFue la primera en revisar la caja negra y los archivos de la estacion.\nDocumento el orden exacto de los apagados: sensores primero, reciclaje despues, alarma al final.\nEse orden inverso al fallo tecnico normal fue lo que la hizo sospechar.",
    consorcio: "CONSORCIO ARTEMIS — Complice institucional\nOrganizacion de investigacion privada con contratos de defensa con gobiernos de 12 naciones.\nFinanciaba el programa NTX-7 (agente neurotrofico) para uso militar.\nConocia y autorizo la metodologia real del experimento CERO.\nFue procesado en 2090 bajo el Tratado de La Haya Espacial, articulo 32."
  },
  examine: {
    ntx7: "El agente NTX-7 es el compuesto neurotrofico sintetico que Cassius estaba probando en la tripulacion.\nFue administrado via el sistema de reciclaje atmosferico de la estacion.\nEn el sistema de ventilacion a dosis de 0.003 mg por metro cubico, actua de forma acumulativa.\nEfecto a los 6 dias: lentitud cognitiva. A los 10 dias: deterioro grave. Sin antidoto conocido.",
    cero: "El experimento CERO era el nombre de codigo de la investigacion de Cassius.\nEl protocolo oficial declaraba 'estudio de adaptacion del SN en microgravedad'.\nEl protocolo real: administracion de NTX-7 a la tripulacion sin su consentimiento.\nEl Consorcio lo sabia y lo aprobo con 'plena autorizacion ejecutiva'.",
    reciclaje: "El sistema de reciclaje atmosferico es el corazon de la supervivencia en la estacion.\nRecicla el CO2 y mantiene los niveles de O2 en todos los modulos.\nCassius tuvo acceso completo a ese sistema como investigador principal.\nApagarlo es una sentencia de muerte para toda la tripulacion.",
    capsula: "La capsula de emergencia personal fue activada por Cassius a las 01:00 del 14 de enero.\nEs la unica capsula de evacuacion individual de la estacion. Estaba reservada para el comandante.\nCassius la uso 15 minutos despues de confirmar la muerte de todos los tripulantes.\nDestino de la capsula: estacion privada ORION-447 del Consorcio Artemis.",
    prometeo: "El nombre de codigo del plan de Cassius para neutralizar a Oretz y matar a la tripulacion.\nApareció en sus comunicaciones internas y en el manifiesto personal.\nIncluia: incapacitar a Oretz, apagar el soporte vital de forma gradual, borrar evidencias y evacuar.\nEl nombre de PROMETEO era conocido por el nivel ejecutivo del Consorcio Artemis.",
    orion: "ORION-447 es una estacion privada del Consorcio Artemis en orbita geoestacionaria.\nFue el destino de evacuacion de Cassius. Llego ahi 6 horas despues de abandonar Helios-3.\nPasó 6 meses ahi antes de que la sonda Artemis y las autoridades orbitales lo localizaran.\nFue detenido el 14 de julio de 2089. Actualmente en proceso ante el Tribunal de La Haya Espacial.",
    oretz: "La comandante Yael Oretz fue la primera en sospechar del experimento.\nEnvio alertas a Tierra el 10 de enero. La respuesta de Control fue filtrada por el Consorcio.\nDecidio cerrar el experimento manualmente la noche del 13 de enero.\nFue a confrontar a Cassius a las 21:00. No regreso en dos horas. Cassius la incapacito.",
    novak: "Petra Novak fue la primera en detectar la manipulacion de los sensores de O2.\nEl 8 de enero noto que alguien habia subido artificialmente la lectura del modulo 3 en un 5%.\nLo reporto a Oretz el 12 de enero. Juntas intentaron acceder al nucleo de sistemas.\nMurio el 14 de enero junto con el resto de la tripulacion.",
    "0322": "Las 00:22 del 14 de enero es la hora en que Cassius apago el sistema de reciclaje global.\nEn ese momento, toda la estacion empezo a perder O2.\nLos registros muestran que lo hizo 18 minutos despues de que la tripulacion del modulo 3 perdiera la consciencia.\nEsperó a estar seguro antes de apagar el sistema global.",
    helio: "HELIO es el codigo de acceso administrativo de la estacion Helios-3.\nFue compartido por Oretz en su mensaje cifrado a su hija Lyra.\nPermite acceder a todos los logs de administrador de la estacion.\nLos logs muestran el historial completo de accesos de Cassius en los 7 dias previos al crimen.",
    lyra: "Lyra Oretz tenia 9 anos cuando su madre murio.\nVive con su padre en Tel Aviv.\nEl nombre de su hija fue el unico codigo que Oretz uso para cifrar su ultimo mensaje.\nEse mensaje contenia el codigo admin de la estacion: HELIO.",
    dao: "Seren Dao llego a los restos de Helios-3 6 meses despues como parte de la mision de recuperacion.\nFue la primera en ver el orden de los apagados en los logs.\nSu intuicion: un fallo tecnico real empieza por los sistemas mas pequeños. Aqui empezo por los sensores.\nEsa observacion fue lo que convirtio un accidente en una investigacion de homicidio.",
    antidoto: "No existe antidoto conocido para el NTX-7 en dosis elevadas.\nCassius lo sabia. Era una de las razones por las que lo eligio como agente de prueba.\nEn dosis bajas cronicas (como en el experimento) el efecto es reversible si se para la exposicion.\nPero en la concentracion final que Cassius aplico, no habia vuelta atras.",
    "control tierra": "Control Tierra recibio las alertas de Oretz el 11 de enero.\nSu respuesta fue: 'No alteren el experimento sin autorizacion nuestra'.\nEsa respuesta fue redactada bajo influencia del Consorcio Artemis.\nEl operador de turno no sabia lo que estaba diciendo en realidad."
  },
  timeline: [
    { time: "01/01/2089", event: "Inicio de ciclo 7. Todo en parametros nominales. Tripulacion de 7 personas.", trigger: "/bitacoras/bitacora_general.txt" },
    { time: "04/01", event: "Cassius solicita ampliar el experimento CERO. Oretz lo deniega.", trigger: "/bitacoras/bitacora_general.txt" },
    { time: "06/01", event: "Cassius continua el experimento sin autorizacion nueva. NTX-7 en reciclaje.", trigger: "/experimentos/resultados_ocultos.enc" },
    { time: "08/01", event: "Novak detecta que los sensores de O2 del modulo 3 han sido falsificados (+5%).", trigger: "/bitacoras/diario_tecnico.txt" },
    { time: "10/01  09:42", event: "Oretz envia alerta urgente a Control Tierra. Pide equipo medico independiente.", trigger: "/comunicaciones/transmision_01.txt" },
    { time: "11/01", event: "Control Tierra responde: 'No alteren el experimento'. Mensaje filtrado por el Consorcio.", trigger: "/comunicaciones/transmision_01.txt" },
    { time: "12/01", event: "Sintomas neurologicos graves en dos tripulantes del modulo 3. Novak informa a Oretz.", trigger: "/bitacoras/bitacora_general.txt" },
    { time: "13/01  20:00", event: "Oretz decide cerrar el experimento manualmente. Va al laboratorio de Cassius.", trigger: "/bitacoras/ultimo_mensaje_oretz.enc" },
    { time: "13/01  21:00", event: "Oretz entra al laboratorio. No regresa. Cassius la incapacita.", trigger: "/sistemas/log_oxigeno.txt" },
    { time: "13/01  23:31", event: "Cassius deshabilita la redundancia del soporte vital del modulo 3.", trigger: "/sistemas/log_oxigeno.txt" },
    { time: "14/01  00:04", event: "Tripulacion del modulo 3 pierde la consciencia.", trigger: "/sistemas/log_oxigeno.txt" },
    { time: "14/01  00:22", event: "Cassius apaga el sistema de reciclaje global. Toda la estacion comienza a morir.", trigger: "/sistemas/log_oxigeno.txt" },
    { time: "14/01  00:45", event: "Cassius borra los logs primarios. Sin signos vitales en ningun modulo.", trigger: "/sistemas/acceso_admin.enc" },
    { time: "14/01  01:00", event: "Cassius activa la capsula personal y abandona la estacion. Destino: ORION-447.", trigger: "/sistemas/acceso_admin.enc" },
    { time: "14/07/2089", event: "Cassius detenido en ORION-447 por la mision de recuperacion Artemis.", trigger: "/conclusion/registro_final.evd" }
  ],
  filesystem: {
    type: "dir",
    children: {
      "bienvenida.txt": { type: "file", content: "HELIOS-3 / NUCLEO DE ARCHIVO\nMision de Recuperacion Artemis — Protocolo POST-EVENTO\nOficial a cargo: Seren Dao / Julio 2089\n\nESTACION HELIOS-3 declarada perdida el 14 de enero de 2089.\nTRIPULACION: 7 personas. SUPERVIVIENTES: 0.\nCAUSA OFICIAL INICIAL: fallo en cadena de soporte vital.\n\nNota de la oficial Dao (registro personal):\n  'Los sistemas no fallan solos de esta manera.\n   El orden de los apagados es lo que me hizo sospechar:\n   primero los sensores, luego el reciclaje, luego la alarma.\n   Un fallo tecnico real sigue el orden inverso.\n   Eso significa que alguien sabia exactamente lo que estaba haciendo.'\n\nDirectorios disponibles:\n  /bitacoras  /experimentos  /comunicaciones  /tripulacion  /sistemas  /consorcio  /conclusion\nComandos: help, ls, cd, read, unlock, search, examine, profile, timeline, evidence, map, hint, clear, menu" },
      bitacoras: {
        type: "dir",
        children: {
          "bitacora_general.txt": { type: "file", content: "BITACORA GENERAL — COMANDANTE YAEL ORETZ\nPeriodo: 1 al 13 de enero de 2089\n\n01/01  Inicio del ciclo 7. Tripulacion completa y en buen estado.\n       7 miembros: Oretz (mando), Cassius (investigacion), Novak (sistemas),\n       Reyes (medicina), Park (operaciones), Lind (comunicaciones), Mara (soporte).\n\n04/01  El Dr. Cassius solicita ampliar el experimento CERO mas alla del protocolo aprobado.\n       Denegage. No firmare nada fuera del protocolo original.\n\n06/01  Cassius continua con el experimento extendido sin mi autorizacion adicional.\n       Le llame al laboratorio. Me dijo que 'los resultados justifican cualquier riesgo'.\n\n08/01  Primera entrada preocupante de Novak: sensores de O2 del modulo 3 alterados.\n       Alguien subio la lectura un 5%. La tripulacion del modulo 3 no lo sabe.\n\n10/01  Transmiti alerta urgente a Control Tierra. Pido equipo medico independiente.\n       Respuesta: minimo 72 horas.\n\n12/01  Sintomas neurologicos en dos tripulantes del modulo 3. Cassius dice que son\n       'reacciones esperadas al protocolo'. Reyes (medico) esta asustado.\n\n13/01  Decidi cerrar el experimento CERO esta noche manualmente.\n       Cassius no lo acepta. Discusion grave en el modulo de mando.\n       Voy al laboratorio ahora mismo. Son las 21:00.\n\n[ULTIMA ENTRADA]" },
          "diario_tecnico.txt": { type: "file", content: "DIARIO TECNICO — ING. PETRA NOVAK\nPeriodo: 8 al 12 de enero de 2089\n\n08/01:\n  Cassius me pidio 'ajustar' los monitores de O2 del modulo 3.\n  Me pregunto si era tecnicamente posible subir la lectura en un 5% sin cambiar el nivel real.\n  Le dije que era posible pero que equivalia a falsificar un sensor de seguridad.\n  Me dijo que era un 'parametro de calibracion experimental'.\n  No lo hice.\n\n09/01:\n  Alguien lo hizo de todas formas. Los monitores del modulo 3 muestran 21.2% de O2.\n  El sensor independiente que tengo en mi terminal muestra 20.2%.\n  La tripulacion del modulo 3 cree que todo esta bien. No lo esta.\n\n11/01:\n  La tripulacion del modulo 3 empieza a quejarse de fatiga inusual.\n  El Dr. Reyes lo atribuyo a 'desincronizacion del ritmo circadiano en microgravedad'.\n  Yo lo atribuyo a la exposicion prolongada a menos O2 del que creen tener.\n\n12/01:\n  Le conte todo a la comandante Oretz. Por fin.\n  Vamos a intentar acceder al nucleo de sistemas esta noche.\n  El protocolo de acceso admin lleva el nombre de la estacion: HELIO.\n\n13/01:\n  Oretz fue al laboratorio a las 21:00. No ha vuelto en mas de dos horas.\n  La puerta del laboratorio esta cerrada desde dentro." },
          "ultimo_mensaje_oretz.enc": { type: "file", locked: true, password: "LYRA", content: "[MENSAJE PERSONAL — COMANDANTE YAEL ORETZ]\nCifrado el 13/01/2089 a las 20:47 (13 minutos antes de entrar al laboratorio)\nDestinatario: Lyra Oretz, 9 anos, Tel Aviv\n\nLyra:\n\nSi lees esto alguna dia es que no regrese.\n\nEl experimento CERO no es lo que nos dijeron que era.\nNo estudiaba como se adapta el sistema nervioso a la microgravedad.\nEstaba probando un agente quimico en nosotros sin decirnos nada.\nUn compuesto que Cassius llama NTX-7.\n\nAlgunos de mis companeros ya tienen sintomas.\nVoy a cerrar el laboratorio esta noche, cueste lo que cueste.\nPero Cassius controla parte del soporte vital desde su laboratorio.\nSi alguien necesita entrar a los logs reales de la estacion,\nel codigo de acceso administrativo es HELIO.\n\nDi a tu papa que le quiero.\nY Lyra: cuando seas mayor, si alguien te dice que el fin justifica los medios,\npiensa en esta noche.\n\nMama." }
        }
      },
      experimentos: {
        type: "dir",
        children: {
          "protocolo_helio.txt": { type: "file", content: "PROTOCOLO OFICIAL — EXPERIMENTO CERO\nInvestigador principal: Dr. Fenn Cassius\nAprobado por: Consorcio Artemis / Comite de Etica (firma del 15/12/2088)\n\nOBJETIVO DECLARADO:\n  Estudio de adaptacion del sistema nervioso central humano\n  a condiciones de microgravedad prolongada.\n\nDURACION APROBADA: 30 dias (ciclo 7 completo)\nSUJETOS: tripulacion completa, con consentimiento informado\nRIESGO DECLARADO: bajo — 'no se administrara ninguna sustancia activa sin consentimiento'\n\n[SEGMENTO CON CORRUPCION DE DATOS]\n\n...administracion de NTX-7 via sistema de reciclaje atmosferico...\n...dosis diaria acumulativa: 0.003 mg por metro cubico...\n...sujetos NO informados para evitar sesgo en la respuesta neuronalt...\n\n[FIN DEL SEGMENTO]\n\nNota de la oficial Dao:\n  'El protocolo oficial y el borrador real son documentos radicalmente distintos.\n   El Comite de Etica firmo el documento oficial, no el real.\n   Alguien presento un documento distinto al que realmente se ejecutaria.'" },
          "resultados_ocultos.enc": { type: "file", locked: true, password: "CERO", content: "RESULTADOS INTERNOS — EXPERIMENTO CERO\nDr. Fenn Cassius / Log de investigacion privado / Enero 2089\n\nDia  1 (01/01): Inicio de administracion de NTX-7 via reciclaje. Dosis: 0.003 mg/m3.\n                Tripulacion sin reacciones visibles. Fase de acumulacion.\n\nDia  4 (04/01): Oretz solicita informacion adicional. Deniega ampliar el protocolo.\n                Ajusto los parametros sin su conocimiento. La dosis sube a 0.004 mg/m3.\n\nDia  6 (06/01): Primeros efectos visibles en modulo 3: lentitud cognitiva, fatiga aumentada.\n                Es exactamente lo esperado. Resultados: EXCELENTES.\n\nDia  8 (08/01): Novak detecto la manipulacion de sensores. Demasiado rapida.\n                Le pedi que lo 'ajustara'. Se nego. Lo hice yo directamente.\n\nDia 10 (10/01): Oretz envio alerta a Tierra. El Consorcio controlara la respuesta.\n                Subo la dosis al 0.006 mg/m3 para acelerar los resultados.\n\nDia 12 (12/01): Efectos graves en el modulo 3. Demasiado rapido.\n                Oretz descubrira todo si no actuo antes del 14.\n\nDia 13 (13/01): Oretz ha decidido cerrar el experimento esta noche.\n                Si CERO se cierra ahora, el Consorcio pierde los contratos ORION.\n                Mas de 1.000 millones en contratos de defensa. Tres anos de trabajo.\n                Voy a activar PROMETEO. No tengo otra opcion razonable.\n\n[Dia 14: vacio — sistema principal apagado a las 00:22]" },
          "cuaderno_ntx7.txt": { type: "file", hidden: true, content: "CUADERNO DE INVESTIGACION — NTX-7 / DR. FENN CASSIUS\nDocumento recuperado del laboratorio de Helios-3\n\nPROPIEDADES CONFIRMADAS DEL NTX-7:\n  — Clase: neuromodulador sintetico de segunda generacion\n  — Soluble en atmosferas de reciclaje aerobico\n  — Indetectable mediante analisis de sangre estandar\n  — Dosis umbral efectiva: 0.002 mg/m3 (acumulacion en 7-10 dias)\n\nEFECTOS DOCUMENTADOS EN FASE CERO:\n  Dias 1-5:   Sin efectos detectables\n  Dias 6-8:   Lentitud cognitiva, fatiga\n  Dias 9-12:  Deterioro neurologico moderado, desorientacion\n  Dias 13+:   Incapacidad motora, perdida de consciencia\n\nPOTENCIAL MILITAR CONFIRMADO:\n  El NTX-7 puede incapacitar una tripulacion o unidad en 6-10 dias\n  sin signos externos de envenenamiento.\n  Aplicacion: control de personal en instalaciones cerradas,\n  neutralizacion de tripulaciones enemigas, interrogatorio avanzado.\n\nNOTA DE CASSIUS (al margen):\n  'El Comite de Etica nunca habria aprobado esto si les hubiera dicho la verdad.\n   Por eso no les dije la verdad.'" }
        }
      },
      comunicaciones: {
        type: "dir",
        children: {
          "transmision_01.txt": { type: "file", content: "TRANSMISION 01 — HELIOS-3 A TIERRA\nFecha: 10/01/2089 — 09:42 UTC\nDE: Comandante Y. Oretz\n\n'Control Tierra, aqui Helios-3.\nSolicito revision urgente del protocolo del investigador Cassius.\nDos tripulantes del modulo 3 presentan deterioro neurologico no previsto.\nSolicito envio de equipo medico independiente en proxima ventana de comunicacion.\nOretz fuera.'\n\n[RESPUESTA DE CONTROL TIERRA — 11/01 — 06:18 UTC]\n'Recibido, Helios-3. Revisaremos los protocolos con el equipo cientifico del Consorcio.\nNo alteren el experimento en curso sin autorizacion del equipo de tierra.\nMas informacion en la proxima ventana. Fin.'\n\nNOTA DE DAO (mision de recuperacion):\n  La respuesta fue redactada por personal del Consorcio Artemis,\n  no por el equipo medico independiente. El operador de turno en Tierra\n  no sabia lo que estaba transmitiendo en realidad.\n  La respuesta fue deliberadamente vaga para ganar tiempo." },
          "alerta_interna.txt": { type: "file", hidden: true, content: "ALERTA DE SISTEMA — 13/01/2089 — 23:47 UTC\nNivel: CRITICO\n\n  MODULO SOPORTE VITAL 3:      FALLO DE REDUNDANCIA\n  Sistema O2 principal modulo 3: OFFLINE\n  Sistema de respaldo modulo 3:  DESHABILITADO MANUALMENTE\n\nORIGEN DEL COMANDO DE DESHABILITATION:\n  Terminal: LAB-01 (Laboratorio principal — Dr. Cassius)\n  Usuario:  f.cassius\n  Hora:     23:31 UTC\n\nNOTA CRITICA:\n  La deshabilitation de la redundancia del soporte vital requiere\n  la confirmacion de DOS oficiales de mando (protocolo de seguridad orbital).\n  Solo se registro la firma de f.cassius.\n  El segundo oficial de confirmacion: CAMPO VACIO.\n\n[No hubo alarma sonora — el sistema de alarma fue silenciado por el mismo usuario]" },
          "transmision_consorcio.txt": { type: "file", hidden: true, content: "TRANSMISION CLASIFICADA — NIVEL EJECUTIVO\nDE: Consorcio Artemis, Directorio Ejecutivo\nPARA: Dr. Fenn Cassius\nFECHA: 12/01/2089 — 14:30 UTC\n\n[COPIA CONSERVADA POR ERROR EN SERVIDOR DE RESPALDO]\n\n'Fenn:\n\nLa situacion con Oretz es un riesgo operativo serio.\nSi el experimento se interrumpe, los contratos ORION se cancelan.\nNo podemos permitir que el informe de Oretz llegue a los medicos independientes.\n\nTienes autorizacion de nivel MAXIMO para proteger el activo.\nActiva PROMETEO si es necesario.\n\nDesde Tierra no intervendremos. Es tu decision.\n\nConsorcio, Nivel Ejecutivo — Protocolo Omega'\n\nNOTA DE DAO:\n  Este mensaje autoriza explicitamente el homicidio de siete personas.\n  'Proteger el activo' y 'PROMETEO' son el mismo eufemismo.\n  Este correo fue el que hundio al Consorcio en el tribunal." }
        }
      },
      tripulacion: {
        type: "dir",
        children: {
          "ficha_oretz.txt": { type: "file", content: "FICHA DE TRIPULACION — COMANDANTE YAEL ORETZ\nCargo: Comandante de estacion, piloto orbital\nEdad: 41. Israelita. En el programa espacial desde 2070.\nMisiones previas: Apolo-L4 (2079), Hermes-2 (2083), Helios-2 (2086).\nFamilia: divorciada. Hija: Lyra Oretz, 9 anos, bajo custodia del padre en Tel Aviv.\n\nEVALUACION (Consorcio, 2088):\n  'Oretz es una comandante capaz pero excesivamente rigida en protocolos.\n   Puede suponer un obstaculo para investigaciones que requieran flexibilidad operativa.'\n\nNOTA DE DAO:\n  'Esa evaluacion la escribio el Consorcio. Lo que llaman flexibilidad operativa\n   es lo que nosotros llamamos violacion de protocolos de seguridad.'" },
          "ficha_cassius.txt": { type: "file", content: "FICHA DE TRIPULACION — DR. FENN CASSIUS\nCargo: Investigador principal, experimento CERO\nEdad: 48. Britanico. Formacion: neurociencia avanzada y farmacologia.\nMisiones previas: 4 misiones clasificadas del Consorcio Artemis.\n\nNOTA DEL CONSORCIO (nivel ejecutivo, confidencial):\n  'Cassius es nuestro activo mas valioso en el programa de control neurotrofico.\n   Ha completado con exito tres protocolos experimentales sin objeciones eticas.\n   Lo consideramos un recurso irreemplazable para el programa ORION.'\n\nNOTA DE DAO:\n  El 'programa de control neurotrofico' es el nombre de cuatro experimentos\n  realizados en instalaciones cerradas sin consentimiento informado.\n  Cassius es el investigador principal de todos ellos." },
          "registro_medico_tripulacion.txt": { type: "file", hidden: true, content: "REGISTRO MEDICO — TRIPULACION MODULO 3\nDr. Reyes, Medico de a bordo / Enero 2089\n\nPERSONAL AFECTADO (modulo 3):\n  Park, J.:  Dias 1-5: normal. Dia 6: fatiga. Dia 10: coordinacion reducida. Dia 12: grave.\n  Lind, E.:  Dias 1-7: normal. Dia 8: confusion leve. Dia 11: desorientacion severa.\n  Mara, S.:  Dias 1-9: normal. Dia 9: cefalea intensa. Dia 12: imposibilidad de comunicarse.\n\nNOTA DEL DR. REYES:\n  'Estos sintomas no tienen explicacion clinica estandar en microgravedad.\n   El patron de aparicion es consistente con exposicion cronica a un agente neurotrofico.\n   Lo documente en la historia clinica pero Cassius me pidio que no lo reportara a Oretz.\n   Le dije que era mi obligacion reportarlo. Al dia siguiente tenia fiebre de 39.\n   No se si fue coincidencia.'" }
        }
      },
      sistemas: {
        type: "dir",
        children: {
          "log_oxigeno.txt": { type: "file", hidden: true, content: "LOG CRITICO — SISTEMAS DE OXIGENO\nHelios-3 / 13 al 14 de enero de 2089\nRecuperado de caja negra (servidor de emergencia autonomo)\n\n21:03  Oretz entra al laboratorio de Cassius (sensor de movimiento)\n21:11  Puerta del laboratorio bloqueada desde el interior (usuario: f.cassius)\n21:19  Silencio en laboratorio — sin comunicaciones registradas durante 2 horas y 12 minutos\n\n23:31  Redundancia de soporte vital modulo 3: DESHABILITADA (usuario: f.cassius)\n23:44  O2 real modulo 3: 18.4% — nivel critico (19% es el umbral de alerta)\n23:52  O2 real modulo 3: 16.1% — tripulacion en confusion severa\n00:04  Tripulacion modulo 3: PERDIDA DE CONSCIENCIA (sensores biometricos)\n00:18  Cassius sale del laboratorio (sensor de movimiento nucleo central)\n00:22  Sistema de reciclaje global: OFFLINE (usuario: f.cassius)\n00:31  O2 en todos los modulos: por debajo del 14% — nivel letal\n00:38  Sin signos vitales en modulo 3\n00:44  Sin signos vitales en ningun modulo de la estacion\n00:45  Logs primarios: BORRADO INICIADO (usuario: f.cassius)\n00:47  Borrado completado — Logs de respaldo NO afectados (caja negra autonoma)\n01:00  Capsula de emergencia personal: LANZADA\n       Usuario: f.cassius / Destino declarado: ORION-447" },
          "acceso_admin.enc": { type: "file", locked: true, password: "HELIO", content: "LOG DE ACCESOS ADMINISTRADOR — NUCLEO HELIOS-3\nRecuperado de caja negra\n\nACCESOS DEL USUARIO f.cassius EN LOS ULTIMOS 7 DIAS:\n\n  08/01  02:14  Modificacion de sensores O2 modulo 3 (lectura +5%)\n  08/01  02:31  Acceso a rutas de ventilacion global\n  10/01  03:45  Consulta de protocolos de emergencia de toda la estacion\n  12/01  15:00  Consulta de procedimiento de deshabilitation de redundancias\n  13/01  20:55  Accede al menu de soporte vital del modulo 3\n  13/01  23:31  Deshabilita redundancias vitales modulo 3\n  14/01  00:22  Apaga el sistema de reciclaje global\n  14/01  00:45  Borra logs primarios\n  14/01  01:00  Activa capsula personal\n\nPLAN DE CASSIUS (llamado PROMETEO en comunicaciones internas):\n  1. Incapacitar a Oretz antes de que cerrara el experimento (21:00-21:11)\n  2. Apagar el soporte vital del modulo 3 de forma gradual\n  3. Esperar a que toda la tripulacion perdiera la consciencia\n  4. Apagar el reciclaje global\n  5. Borrar evidencias digitales\n  6. Evacuar en capsula personal a ORION-447" },
          "manifiesto_cassius.enc": { type: "file", hidden: true, locked: true, password: "PROMETEO", content: "MANIFIESTO PERSONAL — DR. FENN CASSIUS\nEscrito en el laboratorio de Helios-3 el 13/01/2089 — 20:48\nAntes de entrar en contacto con Oretz\n\nLo que hago esta noche lo hago por el avance de la ciencia.\n\nEl agente NTX-7 tiene el potencial de salvar millones de vidas:\npuede neutralizar una amenaza en un espacio cerrado sin fuego cruzado,\nsin bajas civiles, sin destruccion de infraestructura.\nEso es lo que este mundo necesita.\n\nUna tripulacion de siete personas no puede ser el limite de ese potencial.\nOretz no entiende lo que esta en juego.\nEl Consorcio si lo entiende. Y me han dado luz verde.\n\nSi lo que hago esta noche resulta en que yo muero tambien,\npor lo menos los datos de NTX-7 estaran a salvo en los servidores de ORION.\nEl programa continuara.\n\nSi sobrevivo, estare en ORION-447 antes de que encuentren la estacion.\n\nDr. Fenn Cassius — 13 de enero de 2089\n\n[NOTA DE DAO]\n  Cassius sobrevivio. Estuvo en ORION-447 durante seis meses.\n  Fue detenido el 14 de julio de 2089.\n  En ninguna pagina de este manifiesto menciona una sola vez a Oretz, Novak, Park, Lind,\n  Mara, Reyes o a ninguno de los siete que mato esa noche por nombre." }
        }
      },
      consorcio: {
        type: "dir",
        children: {
          "contrato_orion.txt": { type: "file", hidden: true, content: "EXTRACTO DE CONTRATO — PROGRAMA ORION\nConsorcio Artemis / Departamento de Defensa (clasificado)\nRecuperado de servidores del Consorcio por el Tribunal de La Haya Espacial\n\nOBJETO:\n  Desarrollo y entrega de un agente de neutralizacion neurotrofica (NTX-7)\n  para uso en operaciones especiales en entornos cerrados (orbita, submarinos, bases)\n\nVALOR DEL CONTRATO: 1.200 millones USD (en cuatro pagos)\nPLAZO DE ENTREGA: ciclo 7 de Helios-3 (enero 2089)\n\nCONDICION DE PAGO:\n  'Los datos de eficacia en sujetos reales deben incluir:\n   — Dosis umbral de incapacitacion\n   — Tiempo de onset hasta perdida de consciencia\n   — Tasa de exito en entorno cerrado (objetivo: 100%)'\n\nNOTA DEL TRIBUNAL:\n  El contrato exige 'sujetos reales'. El Consorcio sabia que eran humanos.\n  La tripulacion de Helios-3 no era un efecto secundario del experimento.\n  Era el experimento." },
          "acta_ejecutiva.txt": { type: "file", hidden: true, content: "ACTA DE REUNION EJECUTIVA — CONSORCIO ARTEMIS\nNivel: Directorio. Clasificacion: OMEGA\nFecha: 28 de diciembre de 2088 (16 dias antes de Helios-3)\n\nPUNTO 3: Experimento CERO / Helios-3\n\n'El Directorio ha revisado el protocolo del Dr. Cassius.\nLa metodologia real (NTX-7 sin consentimiento) es la unica forma\nde obtener datos de eficacia validados bajo las condiciones que el contrato ORION requiere.\n\nEl Directorio aprueba por unanimidad la metodologia real.\nEl Comite de Etica aprobara el protocolo oficial (version publica).\nCassius opera bajo Protocolo Omega: autorizacion maxima, sin restricciones.\n\nEn caso de exposicion del experimento, se activara el protocolo de cierre PROMETEO.\nCassius ha sido briefeado sobre ese protocolo.'\n\nFIRMAS: [redactadas en el original — restauradas por el tribunal de La Haya]" }
        }
      },
      conclusion: {
        type: "dir",
        children: {
          "registro_final.evd": { type: "file", locked: true, password: "ORION", content: "VEREDICTO FINAL — HELIOS-3\nOficial Seren Dao / Mision de Recuperacion Artemis\nTribunal de La Haya Espacial, articulo 14 / 2090\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nRESPONSABLE DIRECTO: Dr. Fenn Cassius\nRESPONSABLE INSTITUCIONAL: Consorcio Artemis, Directorio Ejecutivo\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nVICTIMAS (7):\n  Cmd. Yael Oretz    — Comandante. Primera en ser incapacitada por Cassius.\n  Ing. Petra Novak   — Sistemas. Habia descubierto la falsificacion de sensores.\n  Dr. Reyes         — Medico. Habia documentado los sintomas del NTX-7.\n  Park, Lind, Mara  — Tripulacion modulo 3. Primeros en perder la consciencia.\n  [Septimo tripulante sin identificar en registros parciales]\n\nMETODO:\n  Cassius administro NTX-7 via el sistema de reciclaje atmosferico durante 13 dias.\n  La noche del 13 de enero incapacito fisicamente a Oretz cuando esta fue a cerrar el experimento.\n  Deshabilito el soporte vital del modulo 3 a las 23:31.\n  Apago el reciclaje global a las 00:22 cuando ya toda la tripulacion habia perdido la consciencia.\n  Borro los logs primarios a las 00:45. Evacuo a las 01:00.\n  La caja negra autonoma no fue afectada por el borrado.\n\nMOTIVO:\n  Preservar los datos del experimento NTX-7 y el contrato ORION del Consorcio Artemis\n  valorado en 1.200 millones de dolares.\n  Si Oretz cerraba el experimento, los datos eran invalidos y el contrato cancelado.\n\nPRUEBAS DETERMINANTES:\n  1. Log de accesos f.cassius (caja negra autonoma) — secuencia de apagados\n  2. Resultados internos del experimento CERO (log privado de Cassius)\n  3. Manifiesto personal de Cassius (PROMETEO)\n  4. Transmision del Consorcio autorizando PROMETEO\n  5. Contrato ORION del Consorcio (exige 'sujetos reales')\n  6. Acta ejecutiva del 28/12/2088 (aprobacion unanime de la metodologia real)\n  7. Diario tecnico de Novak (testigo de la falsificacion de sensores)\n\nSENTENCIA:\n  Dr. Fenn Cassius: cadena perpetua sin beneficio de libertad condicional.\n  Directorio del Consorcio Artemis (8 miembros): penas de 20 a 40 anos.\n  Consorcio Artemis: disuelto por orden del Tribunal de La Haya Espacial en 2091.\n  Contrato ORION: anulado. Material NTX-7: destruido.\n\nEXPEDIENTE CERRADO.\n\n— Seren Dao, Oficial de Recuperacion\n  'En nombre de Yael, Petra, y los cinco que no constan por su nombre.'" }
        }
      }
    }
  },
  databases: {
    doctor: {
      experimento: { text: "Cuaderno de investigacion NTX-7 de Cassius recuperado.", reveal: ["/experimentos/cuaderno_ntx7.txt"] }
    },
    soporte: {
      fallo: { text: "Alerta interna de sistema critico del 13/01 recuperada.", reveal: ["/comunicaciones/alerta_interna.txt"] }
    },
    oxigeno: {
      fallo: { text: "Log critico de sistemas de oxigeno de la caja negra recuperado.", reveal: ["/sistemas/log_oxigeno.txt"] }
    },
    consorcio: {
      contrato: { text: "Extracto del contrato ORION y acta ejecutiva recuperados.", reveal: ["/consorcio/contrato_orion.txt", "/consorcio/acta_ejecutiva.txt"] },
      transmision: { text: "Transmision clasificada del Consorcio a Cassius recuperada.", reveal: ["/comunicaciones/transmision_consorcio.txt"] }
    },
    prometeo: {
      plan: { text: "Manifiesto personal de Cassius accesible (cifrado). Clave en el log de accesos admin.", reveal: ["/sistemas/manifiesto_cassius.enc"] }
    },
    tripulacion: {
      medico: { text: "Registro medico de la tripulacion del modulo 3 recuperado.", reveal: ["/tripulacion/registro_medico_tripulacion.txt"] }
    }
  }
};
